### ISSUE TITLE
model

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#10]
Hi,

From my perspective, each node has each model. For example, in the case of MNIST, we have 4 nodes, after training, there will be 4 models under their own nodes respectively, so how can we get the final model?

Thanks.

**Comment by suresh-ls** [comment]
After Swarm Learning training all the 4 models would have converged and be the same at the end!  One can get the final model by saving the model at the end from any of the nodes (Please refer the mnist_tf.py for details of the model save)
