### ISSUE TITLE
Extended logging

### ISSUE THREAD

**Issue by maestro4** [HewlettPackard/swarm-learning#113]
Is there a way to run SWOP, SN, SWCI containers in the DEBUG mode?

Best Sumit

**Comment by maestro4** [comment]
Also, modifying the SL_LOG_LEVEL to DEBUG in the https://github.com/HewlettPackard/swarm-learning/blob/master/examples/mnist-pyt/swop/swop1_profile.yaml shows no effect.

**Comment by IMOKURI** [comment]
The current version seems to have no effect when DEBUG is set.
It seems to be because too many logs are generated.

I hope that future versions will have logs that are easier to DEBUG...

**Comment by maestro4** [comment]
Is there something planned to see the output of the tasks? For e.g. if I run taskdefs/user_env_pyt_build_task.yaml, I would like to see the output and error stream of docker.

**Comment by IMOKURI** [comment]
In the released https://github.com/HewlettPackard/swarm-learning/releases/tag/v1.1.0, logs of Docker image builds are now output to SWOP logs.

**Comment by suresh-ls** [comment]
Yes, most of the needed output for diagnosing a problem are part of the default SWOP logs !!

Happy debugging!
