### ISSUE TITLE
Source code of swarm-learning library 

### ISSUE THREAD

**Issue by maestro4** [HewlettPackard/swarm-learning#115]
Is there a possibilty to get the source code of swarm-learning library?

I've looked into SWARM-OSP (https://myenterpriselicense.hpe.com/cwp-ui/product-details/SWARM-OSP/-/sw_osp) and couldn't find the source code of classes such as swarumutils, swopruntask etc.

**Comment by RadhakrishnaJ** [comment]
Currently Swarm core functionality is proprietary to HPE.
