### ISSUE TITLE
Not able to run sn not on the version 0.0.3

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#118]
Hello, 
I am having this error which i am not able to resolve 
![errors](https://user-images.githubusercontent.com/77096343/183104288-a86163ab-f44c-4105-8395-5c18706710e6.png)
Could not open file or uri for loading certificate from -
808B177A8C7F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
808B177A8C7F0000:error:80000002:system library:file_open:No such file or directory:../providers/implementations/storemgmt/file_store.c:267:calling stat(-)
Unable to load certificate
Error: spiffeid: invalid scheme
run-sn: cannot generate join token

**Comment by RadhakrishnaJ** [comment]
Hi Oliver, are you using 0.3.0 Eval version?

**Comment by oliversaldanha25** [comment]
Yes. We came from Aachen to Dresden so setting it up in the new location. All the systems have this same error. Is it the network issue or the systems issue ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by suresh-ls** [comment]
Hi Oliver,
We would encourage you to move on to the latest 1.1.0 version!  We wouldn't be able to support the old 0.3.0 version.

- It needs just a trivial change to the ML application.. Just need to change the python import statement..  Post that it should work as is in the new version.

- There would be minor changes to the start-up run scripts.  It brings in a lot of simplification & also we have automated way of launching your ML workloads using the new SWOP functionality!   

Please plan for moving to the latest version and do reach out if there is any issue while moving on to 1.1.0
