### ISSUE TITLE
RuntimeError: No identity specified

### ISSUE THREAD

**Issue by hanyu1980** [HewlettPackard/swarm-learning#119]
Hi,

I start SN sentinel Node(version 1.0.0), but sn docker container don't run.

The following commands I used:

$ ./bin/run-sn --name sn121 --host-ip 192.168.56.121 --sentinel --sn-api-port 30304 --sn-p2p-port 30303  --apls-ip 192.168.56.1 --apls-port 5814

$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

$ docker ps -a
CONTAINER ID   IMAGE                                                              COMMAND                  CREATED          STATUS                      PORTS     NAMES
c6f9b63813e1   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sn:1.0.0   "/usr/bin/python3 -c…"   44 minutes ago   **Exited** (1) 43 minutes ago             sn121

$ docker logs sn121
\######################################################################
\##                    HPE SWARM LEARNING SN NODE                    ##
\######################################################################
\## © Copyright 2019-2022 Hewlett Packard Enterprise Development LP  ##
\######################################################################
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_sn.py", line 57, in start_swarm_sn.main
  File "id.py", line 174, in id.id.ID.acquireIdentity
**RuntimeError: No identity specified**

How do i fix it?

**Comment by htjain** [comment]
run-sn command missing key and cert parameters. 
Please follow cert generation steps from one of the examples and try again.
https://github.com/HewlettPackard/swarm-learning/blob/master/examples/mnist/MNIST.md

**Comment by hanyu1980** [comment]
> run-sn command is missing key and cert parameters. Please follow cert generation steps from one of the examples and try again. https://github.com/HewlettPackard/swarm-learning/blob/master/examples/mnist/MNIST.md

**Comment by hanyu1980** [comment]
> run-sn command is missing key and cert parameters. Please follow cert generation steps from one of the examples and try again. https://github.com/HewlettPackard/swarm-learning/blob/master/examples/mnist/MNIST.md

OK, thank you！
