### ISSUE TITLE
Not able to connect to License Server 

### ISSUE THREAD

**Issue by suresh-ls** [HewlettPackard/swarm-learning#12]
Tried again on the VMware Workstation with Ubuntu 20.04 and got the same error.
BTW, got warning "SSL certificate problem: self signed certificate" when testing accessibility with curl and I am not sure if it is related to my problem.

_Originally posted by @wzp21142 in https://github.com/HewlettPackard/swarm-learning/issues/7#issuecomment-869710142_

**Comment by suresh-ls** [comment]
Can you confirm:

1. Are you are running run-sl script on the same node where you have started the License Server ?

2. Is all the 4 env variables are set ? ( as mentioned in step 2 of https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-keras#readme )
If yes, give the o/p of the "echo" of the 4 variables ?

3. Provide the o/p of  "docker ps | grep swarm"

**Comment by wzp21142** [comment]
> Can you confirm:
> 
> 1. Are you are running run-sl script on the same node where you have started the License Server ?
> 2. Is all the 4 env variables are set ? ( as mentioned in step 2 of https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-keras#readme )
>    If yes, give the o/p of the "echo" of the 4 variables ?
> 3. Provide the o/p of  "docker ps | grep swarm"

1.Yes.

2.Yes. Take the terminal of node2 as an example:
APLS_IP=127.0.0.1
EXAMPLE=mnist-keras
WORKSPACE_DIR=/home/***/swarm-learning/examples
TRAINING_NODE=node2
3.
20ae9016d3d1   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/spire-server:0.3.0   "/spire/bin/launcher"    About a minute ago   Up About a minute                                               node-spire
d1c87c53a670   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0           "/opt/autopass/Autop…"   13 minutes ago       Up 13 minutes       0.0.0.0:5814->5814/tcp, :::5814->5814/tcp   trusting_feistel

**Comment by wzp21142** [comment]
Tested running License Server in VMware and the run-sl script in WSL and it seems to work fine. This error appears to be caused by the first point @suresh-ls mentioned.

**Comment by RadhakrishnaJ** [comment]
Since user has confirmed License server is working fine, this issue can be closed now.
