### ISSUE TITLE
I can not download the AutoPass License Server

### ISSUE THREAD

**Issue by shenhai1895** [HewlettPackard/swarm-learning#120]
I have got the License. However, I can not download the AutoPass License Server.

The error message is "HPE regrets to inform you that we are unable to act on your access request at this time due to technical issues we are currently experiencing with user validation.

To proceed please [submit](https://myenterpriselicense.hpe.com/cwp-ui/contact-us) a site support request for assistance and we will help you shortly."

**Comment by htjain** [comment]
Its working for me, can you please try again ?
If you are still not working please contact support team at https://myenterpriselicense.hpe.com/cwp-ui/contact-us

**Comment by suresh-ls** [comment]
Hope the you are able to download the license server.  Please file a request with the above URL, if its still a issue.
Closing this issue.
