### ISSUE TITLE
Problems about starting SN node

### ISSUE THREAD

**Issue by TempTation1** [HewlettPackard/swarm-learning#125]
Hi. I'm running a basic demo about mnist-keras. But stuck when starting a SN container. The logs of container sn are as follows.

![sn-node](https://user-images.githubusercontent.com/43208353/188545137-58528763-7dbc-421d-a83b-8366d81086b8.png)

It just stuck here and I could not see the message “Starting SWARM-API-SERVER on port: xxxxx”. Looks like it didn't start successfully. If I override it and start a sl-node, it will report an error like "Failed to connect to the API server. Retrying x of 12"

![TY5G@V~C D}7W2VLJ2A`BOT](https://user-images.githubusercontent.com/43208353/188546555-9b5178ea-8bd2-4af0-bca4-9d2d6fb2ce47.png)

The command of starting the sn container is 
**./run-sn --name=node-sn --host-ip=192.168.179.128 --sentinel-ip=192.168.179.128 --sn-p2p-port=10000 --sn-api-port=11000 --sn-fs-port=12000 --apls-ip=192.168.179.128 -serverAddress=192.168.179.128 -genJoinToken**

The command of starting the sl node is
**./run-sl --name=node-sl --sl-platform=TF --host-ip=192.168.179.128 --sn-ip=192.168.179.128 --sn-api-port=11000 --sl-fs-port=16000 --data-dir=xxxxx/mnist-keras/app-data --model-dir=xxxxx/mnist-keras/model --model-program=mnist_tf.py --apls-ip 192.168.179.128 -serverAddress 192.168.179.128 -genJoinToken**

192.168.179.128 is the IP address of Ubuntu 20.04 virtual machine working on the VMware. The swarm learning version is 0.3.0. All images were pulled correctly.

Before I run the sn container, I have started the APLS server, installed licenses and started the spire server. Logs and commands are in the pictures as follows:
![license](https://user-images.githubusercontent.com/43208353/188545854-b009d1f7-ade2-4080-8770-279f7817ec6e.png)

![spire](https://user-images.githubusercontent.com/43208353/188545883-b38048f2-9463-4b3b-b8fa-2c29fc47f484.png)

All container were started on the same virtual machine. The user id has been set as a member of the docker group.
Looking forward to someone helping me. 
In addition. Socket.timeout problem in issue 59 also occured before. Maybe the two problems have some relations.

**Comment by htjain** [comment]
SN node takes some time to start.  Please check cpu usage of geth process, once its stable check sl logs. 

Also please try latest swarm release 1.1.0.

**Comment by TempTation1** [comment]
> SN node takes some time to start. Please check cpu usage of geth process, once its stable check sl logs.
> 
> Also please try latest swarm release 1.1.0.

Thanks for your reply!
Just now I started it again and faced the problem in issue 59, I don't know how to solve the problem.
![1662441060173](https://user-images.githubusercontent.com/43208353/188551802-c9e259ab-db3a-4706-a229-ecebd7689e1c.jpg)

By the way, how long does it take to start the sn node. I have been waiting it for a long time but it still stuck in the location I mentioned.
And, about swarm release 1.1.0. When I tried to install the apls-9.10.2, I failed. That's why I turned to the version 0.3.0.
![1662441304074](https://user-images.githubusercontent.com/43208353/188552298-8c291e89-80bd-402f-9132-00a21f908d5f.jpg)

**Comment by TempTation1** [comment]
> SN node takes some time to start. Please check cpu usage of geth process, once its stable check sl logs.
> 
> Also please try latest swarm release 1.1.0.

After I started the sn container, I used top to monitor and saw the CPU usage of the geth fluctuates between 200-300.
Then I started the sl node, the logs are as follows.
![sl不行cpu占用](https://user-images.githubusercontent.com/43208353/188563057-4109b46d-0bcf-4247-ba8d-d99d96bf6a23.png)

So I guess my laptop is too weak?......Or other errors still exist?

**Comment by htjain** [comment]
How many cores are allocated to VM?  I would suggest start `sl` after SN is ready for connections. 

For 1.1.0 download issue, please open a support ticket from link provided on error page. Someone from MSC team will check your account issue.

**Comment by htjain** [comment]
@TempTation1 With 4 cores start would be bit slow but should be enough for basic testing.  
Wait for following in sn logs before starting other containers.

> swarm.blCnt : INFO : Starting SWARM-API-SERVER on port: 30304

**Comment by TempTation1** [comment]
> @TempTation1 With 4 cores start would be bit slow but should be enough for basic testing. Wait for following in sn logs before starting other containers.
> 
> > swarm.blCnt : INFO : Starting SWARM-API-SERVER on port: 30304

I'm so sorry to reply u so late cause I've been busy with other things recently.
4 cores were enough. I tried to wait for about 10 minutes and it started successfully. Now I can run the programs on a server instead of using a PC.
Thanks for your guidance!
