### ISSUE TITLE
SN failed to start with swarm-learning version 1.1.0

### ISSUE THREAD

**Issue by h-ahmad** [HewlettPackard/swarm-learning#126]
#  Issue description
- issue description: SN is started with old version of swarm-learning while it is failed when upgraded version 1.1.0
- occurrence - consistent or rare: Recursive
- error messages: Error message is attached below.

![image](https://user-images.githubusercontent.com/28649744/189119563-be8eaa67-55f9-4115-94e7-7f40e601361a.png)

- commands used for starting containers: Command is shown in above screenshot.
- docker logs [APLS, SPIRE, SN, SL, SWCI]: Docker container not started.

# Swarm Learning Version:
- Find the docker tag of the Swarm images ( $ docker images | grep hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning )

# OS and ML Platform
- details of host OS: Ubuntu 20.04
- details of ML platform used: 
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): Default as given in example.

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses? Yes 
- If Multiple systems are used, can each system access every other system? Yes
- Is Password-less SSH configuration setup for all the systems? Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? Yes
- Is the user id a member of the docker group? Yes

# Additional notes
- Are you running documented example without any modification? Yes.
- Every thing is by default. 
- HPE License server is working. 
- It works when I replace new folder 'swarm-learning' with the old one. But SN node is not started with the new swarm-learning folder in the directory '/opt/hpe/swarm-learning'.

**Comment by dotrywhile-wm** [comment]
why i can't download the software APLS. The page say that "HPE regrets to inform you that we are unable to act on your access request at this time due to technical issues we are currently experiencing with user validation."

**Comment by dotrywhile-wm** [comment]
Would you give me the install package of APLS？ please!

**Comment by iArpanPatel** [comment]
@h-ahmad, could you please confirm if this is resolved or not?? 
You can try our [latest release 2.0.0](https://github.com/HewlettPackard/swarm-learning/releases/tag/v2.0.0)

**Comment by iArpanPatel** [comment]
Closing this issue, as there is no response. Please re-open if you face the issue again.
