### ISSUE TITLE
Docker repository login issues

### ISSUE THREAD

**Issue by maestroe** [HewlettPackard/swarm-learning#128]
I'm having problem while installing the swarm learning 1.1.0 software. Installation stops at "Logging into docker registry" which fails with "Error: Unable to log in to the HPE docker registry. Please make sure you enter a valid HPE Passport Username.".

I can successfully log into https://myenterpriselicense.hpe.com/ with my email address.

Also, `docker login hub.myenterpriselicense.hpe.com -u <my_email_address> -p hpe_eval` fails with "Error response from daemon: login attempt to https://hub.myenterpriselicense.hpe.com/v2/ failed with status: 401 Unauthorized".

Any suggestions?

**Comment by mchernicoff** [comment]
I am having the same problem with the installer. I have tried running the installer both in an Ubuntu VM and on a Windows machine, and I get the same error message both times.

**Comment by h-ahmad** [comment]
Yes, it gives error while connecting to all nodes. But it creates 'lib' folder in 'swarm-learning' folder if ssh is working properly. So you can proceed with this error as it creates library folder and every thing works. I have successfuly run it.

**Comment by maestroe** [comment]
> We need to download the newer version (1.1.0) from HP site. 

From where exactly? As far as I know, the docker images for SN, SWCI, SWOP, SL are only available through the docker https://hub.myenterpriselicense.hpe.com/ .

**Comment by maestroe** [comment]
The docker hub is reachable again. The issue has been resolved, therefore, closing the ticket.
