### ISSUE TITLE
the examle of  minst-karas problem

### ISSUE THREAD

**Issue by thunder2016** [HewlettPackard/swarm-learning#13]
(1) Problem describe:
I build the enviroment for swarm-learning which in vmware enviroment ubuntu20.04.
I  build the environment follow the minst-karas document , everything goes well until I configrate the node1 terminal.
some error had happend as follow:
WARN[0000] Current umask 0022 is too permissive; setting umask 0027 
INFO[0000] Starting agent with data directory: "/spire/data/agent" 
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=join_token plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=false plugin_name=swarm plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Bundle is not found                           subsystem_name=attestor
INFO[0000] SVID is not found. Starting node attestation  subsystem_name=attestor
WARN[0000] Insecure bootstrap enabled; skipping server certificate verification  subsystem_name=attestor
INFO[0000] Node attestation was successful               spiffe_id="spiffe://swarm.learning/spire/agent/join_token/0607a704-36e3-4d9a-a50d-03a18b3263e3" subsystem_name=attestor
INFO[0000] Starting Workload and SDS APIs                subsystem_name=endpoints
2021-06-29 02:57:28,312 : swarm.mlApp : INFO : Creating Autopass License Provider
Jun 29, 2021 2:57:28 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/platform/swarmml/autopassj/lib/jaxb-impl-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-06-29 02:57:29,158 : swarm.mlApp : INFO : Creating license server
2021-06-29 02:57:29,158 : swarm.mlApp : INFO : Setting license servers
2021-06-29 02:57:29,173 : swarm.mlApp : INFO : Acquiring floating license 1100000378:1
2021-06-29 02:57:29,776 : swarm.mlApp : ERROR : acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_ml.py", line 97, in start_swarm_ml.main
  File "manager.py", line 157, in manager.acquireLicense
  File "alp.py", line 321, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "swarmutils.py", line 619, in swarmutils.swarmlogger.emitError
RuntimeError: acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
2021/06/29 02:57:30 exit status 1

**Comment by oliversaldanha25** [comment]
Even I am having the same error. Can I get the solution?

**Comment by suresh-ls** [comment]
From the error, it looks like license server config issue.

1) Hope the license server is started with run_apls script.  After starting it, have you installed the required license file that is downloaded from the HPE MSC page ? ( As mentioned under "Getting Started" ->"Download and setup docker images and evaluation licenses" section of the main README )

2) Hope all the 3 required swarm learning containers are running – node-sn, node-spire & apls (License server), before we start the SL container.  Run 'docker ps | grep swarm' and get the o/p.  

3)	Is all the 4 env variables are set on the terminal where you are starting the run-sl script ? If yes, give the o/p of the "echo" of the 4 variables ?

4)	Also, what system are you running this ? OS version ?

**Comment by oliversaldanha25** [comment]
Hello: Thanks for your quick reply.
1. I have run the license server is started with run_apls script the output is given below
o/p:oliver@oliver-VirtualBox:~/swarm-learning/swarm-learning/bin$ ./run-apls
[sudo] password for oliver: 
+++ dirname /opt/autopass/AutopassLicenseServer/bin/entrypoint
++ realpath /opt/autopass/AutopassLicenseServer/bin/..
+ aplsRootDir=/opt/autopass/AutopassLicenseServer
+ aplsInstallDir='/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server'
+ aplsBinDir='/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin'
+ '/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/startup.sh'
Using CATALINA_BASE:   /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server
Using CATALINA_HOME_HPAPLS:   /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server
Using CATALINA_TMPDIR: /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/temp
Using JRE_HOME:        /opt/autopass/AutopassLicenseServer/jre
Using CLASSPATH:       /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/bootstrap.jar:/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/tomcat-juli.jar
Tomcat started.
+ true
+ nc -z 127.0.0.1 5814
+ [[ 1 -eq 0 ]]
+ sleep 5
+ true
+ nc -z 127.0.0.1 5814
+ [[ 0 -eq 0 ]]
+ break
++ ps -C java -opid --no-header
++ tr -d ' '
+ aplsPID=19
+ echo 'Waiting for APLS pid 19 to terminate'
Waiting for APLS pid 19 to terminate
+ tail --pid=19 -f /dev/null



2. When I run: run-spire-server 
o/p:
oliver@oliver-VirtualBox:~/swarm-learning/swarm-learning/bin$ ./run-spire-server
[sudo] password for oliver: 
WARN[0000] The configured SVID TTL cannot be guaranteed in all cases - SVIDs with shorter TTLs may be issued if the signing key is expiring soon. Set a CA TTL of at least 6x or reduce SVID TTL below 6x to avoid issuing SVIDs with a smaller TTL than specified 
WARN[0000] The configured SVID TTL cannot be guaranteed in all cases - SVIDs with shorter TTLs may be issued if the signing key is expiring soon. Set a CA TTL of at least 6x or reduce SVID TTL below 6x to avoid issuing SVIDs with a smaller TTL than specified 
WARN[0000] Current umask 0022 is too permissive; setting umask 0027 
INFO[0000] Data directory: "/spire/data/server"         
INFO[0000] Opening SQL database                          db_type=sqlite3 subsystem_name=built-in_plugin.sql
INFO[0000] Initializing new database                     subsystem_name=built-in_plugin.sql
INFO[0000] Connected to SQL database                     read_only=false subsystem_name=built-in_plugin.sql type=sqlite3 version=3.25.2
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=join_token plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=noop plugin_services="[]" plugin_type=NodeResolver subsystem_name=catalog
INFO[0000] Plugins started                              
INFO[0000] Journal loaded                                jwt_keys=0 subsystem_name=ca_manager x509_cas=0
INFO[0000] X509 CA prepared                              expiration="2021-07-07T16:49:34Z" issued_at="2021-06-30T16:49:34Z" self_signed=true slot=A subsystem_name=ca_manager
INFO[0000] X509 CA activated                             expiration="2021-07-07T16:49:34Z" issued_at="2021-06-30T16:49:34Z" slot=A subsystem_name=ca_manager
INFO[0000] JWT key prepared                              expiration="2021-07-07T16:49:34Z" issued_at="2021-06-30T16:49:34Z" slot=A subsystem_name=ca_manager
INFO[0000] JWT key activated                             expiration="2021-07-07T16:49:34Z" issued_at="2021-06-30T16:49:34Z" slot=A subsystem_name=ca_manager
INFO[0000] Building in-memory entry cache                subsystem_name=endpoints
INFO[0000] Completed building in-memory entry cache      subsystem_name=endpoints
INFO[0000] Starting TCP server                           address="[::]:8081" subsystem_name=endpoints
INFO[0000] Starting UDS server                           address=/tmp/spire-registration.sock subsystem_name=endpoints
Entry ID         : 249df2c7-4221-41fc-9aa0-e1c44cb103fe
SPIFFE ID        : spiffe://swarm.learning/swarm/sn
Parent ID        : spiffe://swarm.learning/swarm/sn-agent
Revision         : 0
TTL              : default
Selector         : swarm:node-type:sn
DNS name         : swarm-network-node

Entry ID         : 8f503e30-9231-43ad-9903-4facc0c1591a
SPIFFE ID        : spiffe://swarm.learning/swarm/sl
Parent ID        : spiffe://swarm.learning/swarm/sl-agent
Revision         : 0
TTL              : default
Selector         : swarm:node-type:sl
DNS name         : swarm-learning-node

Entry ID         : cc06a647-81a9-4881-a000-fd6611ed8199
SPIFFE ID        : spiffe://swarm.learning/swarm/swci
Parent ID        : spiffe://swarm.learning/swarm/swci-agent
Revision         : 0
TTL              : default
Selector         : swarm:node-type:swci
DNS name         : swci-node

3. The error is when I run : run-sn
o/p:
oliver@oliver-VirtualBox:~/swarm-learning/swarm-learning/bin$ ./run-sn --host-ip=134.61.173.231 --sentinel-ip=134.61.173.231
server_address must be configured
2021-06-30 16:58:38,239 : swarm.blCnt : INFO : Setting up blockchain layer for the swarm node: START
2021-06-30 16:58:38,999 : swarm.blCnt : INFO : Creating Autopass License Provider
Jun 30, 2021 4:58:39 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/platform/swarmbl/autopassj/lib/jaxb-impl-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-06-30 16:58:39,706 : swarm.blCnt : INFO : Creating license server
2021-06-30 16:58:39,707 : swarm.blCnt : INFO : Setting license servers
2021-06-30 16:58:39,721 : swarm.blCnt : INFO : Acquiring floating license 1100000380:1
2021-06-30 16:58:40,271 : swarm.blCnt : ERROR : acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000380:1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_sn.py", line 61, in start_swarm_sn.main
  File "manager.py", line 157, in manager.acquireLicense
  File "alp.py", line 321, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "swarmutils.py", line 619, in swarmutils.swarmlogger.emitError
RuntimeError: acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000380:1
2021/06/30 16:58:40 exit status 1
oliver@oliver-VirtualBox:~/swarm-learning/swarm-learning/bin$ sudo docker ps | grep swarm
f0012e28ebd8   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/spire-server:0.3.0   "/spire/bin/launcher"    9 minutes ago    Up 9 minutes                             relaxed_davinci
d512d098cbed   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0           "/opt/autopass/Autop…"   14 minutes ago   Up 14 minutes   0.0.0.0:5814->5814/tcp   frosty_banzai

4. I am using the Linux operating system: Ubuntu20.04 on a ThinkPad i7

**Comment by suresh-ls** [comment]
Ok..  Looks like you have NOT installed the license.dat file ?

Have you installed the required license file that is downloaded from the HPE MSC page ? ( As mentioned under "Getting Started" ->"Download and setup docker images and evaluation licenses" section of the main README ).      

Please refer HPE auto pass license server.pdf for installation of license files.
https://github.com/HewlettPackard/swarm-learning/blob/master/docs/HPE%20AutoPass%20License%20Server%20User%20Guide.pdf

**Comment by oliversaldanha25** [comment]
1. I have downloaded and installed the license. But it is taking an IP 127.0.0.1 which is not my system IP.
2. How do I do the configuration to my system?
3. I am very new to swarm learning so I think I may be missing some basic things, can I get some help?

**Comment by oliversaldanha25** [comment]
![installation](https://user-images.githubusercontent.com/77096343/124093848-82b7e880-da58-11eb-9ab5-01c71c8d8ca1.GIF)
![image](https://user-images.githubusercontent.com/77096343/124093979-9fecb700-da58-11eb-909a-cd45f5f00ac3.png)

**Comment by oliversaldanha25** [comment]
I think there is a configuration error
![image](https://user-images.githubusercontent.com/77096343/124129539-29fb4680-da7e-11eb-8e23-de97719babbb.png)

**Comment by oliversaldanha25** [comment]
I do not understand what is the mail server which I have to enter
![image](https://user-images.githubusercontent.com/77096343/124129682-50b97d00-da7e-11eb-885b-98d88dbaa21d.png)

**Comment by thunder2016** [comment]
I think  the mail server  dose not matter.Download license.dat file and install it in the web . 
set   APLS_IP = your_host_IP    for example: APLS_IP = 192.168.37.131

**Comment by oliversaldanha25** [comment]
Now i get the same old error
![image](https://user-images.githubusercontent.com/77096343/124131701-5748f400-da80-11eb-979a-b555e4488e80.png)

**Comment by thunder2016** [comment]
could you show me  your license.dat file.

**Comment by oliversaldanha25** [comment]
If you dont mind can we connect and have a look at it together. It will be more convenient. 
![image](https://user-images.githubusercontent.com/77096343/124132253-e8b86600-da80-11eb-8708-016fe036cbd2.png)

**Comment by thunder2016** [comment]
OK,what can I do for you.

**Comment by oliversaldanha25** [comment]
Could you please send me an email to osaldanha@ukaachen.de or give me your mail-id.

**Comment by thunder2016** [comment]
my email is 798213337@qq.com

**Comment by RadhakrishnaJ** [comment]
Hello, 
As the actual issue is resolved, this ticket can be closed if no further comments on issues. Please add if you have any comments. 

For any further discussions requesting you to start a new thread  in Discussions forum.
