### ISSUE TITLE
Opening pipes to communicate with user container ...

### ISSUE THREAD

**Issue by h-ahmad** [HewlettPackard/swarm-learning#134]
#  Issue description
- issue description: I am running 'fraud-detection' example on a single SN node which uses 4 ML/SL nodes as given in the example.
- occurrence:  consistent
- error messages: Opening pipes to communicate with user container ...
- commands used for starting containers: SN, SWOP, and SWCI run successfully. The error is raised on SL nodes after running SWCI command.
- docker logs [APLS, SPIRE, SN, SL, SWCI]: 
- APLS
![image](https://user-images.githubusercontent.com/28649744/199215690-05f8fbfb-85ef-490c-a92f-e06d7e1aec10.png)
- SPIRE
![image](https://user-images.githubusercontent.com/28649744/199222982-2e5734e1-5e7c-4239-97ed-ad9b61eff375.png)
- SN
![image](https://user-images.githubusercontent.com/28649744/199218276-8f51b622-dee9-46b8-8a81-f1c8d2cbe4a4.png)
- SL
![image](https://user-images.githubusercontent.com/28649744/199223106-f0d6c807-404a-4834-abf7-558c1f8324f1.png)
- SWCI
![image](https://user-images.githubusercontent.com/28649744/199223191-020c9060-13a6-4d5b-84dc-f7f4a85ffa95.png)
# Swarm Learning Version: 1.1.0
- Find the docker tag of the Swarm images ( $ docker images | grep hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning )
![image](https://user-images.githubusercontent.com/28649744/199216328-21afccd6-451d-4058-99ed-045c85c0dddc.png)
# OS and ML Platform
- details of host OS:  Ubunt 22.04
- details of ML platform used: Python 3.10
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 
Number of machine = 1, 
SL/ML nodes = 4, 
SN node = 1
# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses? Yes
- If Multiple systems are used, can each system access every other system? Yes
- Is Password-less SSH configuration setup for all the systems? Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? Yes
- Is the user id a member of the docker group? Yes 

# Additional notes
- Are you running documented example without any modification?  Yes
- Add any additional information about use case or any notes which supports for issue investigation:

**Comment by yzzer123** [comment]
Did you solve this problem? Could you share some tips to solve it?

**Comment by h-ahmad** [comment]
> * ing containers: SN,

Are you facing problem with your ML model? If it's related to configuration, you need to explain your setup environment for all nodes.

**Comment by yzzer123** [comment]
SL container output the "Opening pipes to communicate with user container" log. SN work well. How did you solve it ?
