### ISSUE TITLE
Install package on pytorch platform

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#15]
Hi，

Could you please tell me how to install package on pytorch platform？ I want to try my case.

Thanks.

**Comment by suresh-ls** [comment]
It's mentioned in our FAQ already :-) Please refer:
https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md 

Quoting it again here:
**Can one add new python packages in Swarm Learning?**

Yes. If user needs additional packages, he can spawn a shell in the Swarm Learning (SL) container and add the required packages. He can also do a docker commit to persist this across restarts.

**Comment by difan0224** [comment]
It does not work to use pip when in container like pyt.
