### ISSUE TITLE
how to use the ML docker image that has been built in advance

### ISSUE THREAD

**Issue by hanyu1980** [HewlettPackard/swarm-learning#151]
If I want to execute RUN_ SWARM TASK by SWCI, how to use the ML docker image that has been built in advance? 

I don't want to use MAKE_ USER_ CONTAINER TASK build again.

**Comment by IMOKURI** [comment]
I feel that PULL_IMAGE could be used instead of MAKE_USER_CONTAINER.

However, I don't think it is currently possible to execute RUN_SWARM without using either.

**Comment by hanyu1980** [comment]
> I feel that [PULL_IMAGE](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/User/Task_for_pulling_a_prebuilt_Docker_image.md) could be used instead of MAKE_USER_CONTAINER.
> 
> However, I don't think it is currently possible to execute RUN_SWARM without using either.

My current solution is the same as yours: execute ML for the first time by MAKE_ USER_ CONTAINER + RUN_ SWARM, execute ML again by PULL_ IMAGE + RUN_ SWARM.
I think this method is troublesome. Is there any way to directly execute RUN_ SWARM?
