### ISSUE TITLE
How to install package on sl-pyt?

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#17]
The pyt relies on the address server. How to install package on sl-pyt?

**Comment by RadhakrishnaJ** [comment]
Hello, 

I am not getting the context of your question. 
Please provide some more details on what is your need for additional package installation?

**Comment by difan0224** [comment]
For example, I want to use cv2. But it seems there is no this package opencv-python inside.

**Comment by RadhakrishnaJ** [comment]
Hello,

For any additional packages support to machine learning process, user has to do following. 
1.	Write a dockerfile to create a local SL image
  •	By extending FROM the default SL image (**sl-tf** or **sl-pyt**). 
  •	Add required additional packages 
2.	Build the local SL image from above dockerfile. 
3.	If local SL image name differs from default SL image, then update ‘common’ script (inside swarm-learning/bin) and make sure following lines uses local SL image.  
slTFImage="${swarmDockerHubAndUser}/sl-tf:${swarmVer}" (or) 
slPytImage="${swarmDockerHubAndUser}/sl-pyt:${swarmVer}"
4.	As usual run the container using run-sl command.

**Comment by malikre** [comment]
Closing this issue as instructions provided on the initial query. Please open a new issue in case any further assistance required.
