### ISSUE TITLE
Pull access denied for user-ml-env-tf2.7.0

### ISSUE THREAD

**Issue by PNg-HA** [HewlettPackard/swarm-learning#191]
#  Issue description
- issue description: When I follow the example CIFAR-10 in HPE Swarm Learning User Guide, I cannot access to the ml-image in step 9.
- error messages: `Error response from daemon: pull access denied for user-ml-env-tf2.7.0, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/02bc1507-2cd0-4129-b496-69951a9bb4b9)
- command to run SN: `./scripts/bin/run-sn -d --rm --name=sn1 --host-ip=${HOST_1_IP} --sentinel --sn-api-port=${SN_API_PORT} --key=workspace/cifar10/cert/sn-1-key.pem --cert=workspace/cifar10/cert/sn-1-cert.pem --capath=workspace/cifar10/cert/ca/capath --apls-ip=${APLS_IP}`
- command to run SL: `./scripts/bin/run-sl -d --name=sl1 --host-ip=${HOST_1_IP} --sn-ip=${SN_IP} --sn-api-port=${SN_API_PORT} --sl-fs-port=${SL_1_FS_PORT} --key=workspace/cifar10/cert/sl-1-key.pem --cert=workspace/cifar10/cert/sl-1-cert.pem --capath=workspace/cifar10/cert/ca/capath --ml-image=user-ml-env-tf2.7.0 --ml-name=ml1 --ml-w=/tmp/test --ml-entrypoint=python3 --ml-cmd=model/cifar10.py --ml-v=workspace/cifar10/model:/tmp/test/model --ml-e MODEL_DIR=model --ml-e MAX_EPOCHS=1 --ml-e MIN_PEERS=2 --ml-e https_proxy= --apls-ip=${APLS_IP}`
- docker logs [APLS, SPIRE, SN, SL, SWCI]: 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/998a8b92-bc42-4f8b-ac38-ca737c4f4e6c)
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/1e351008-2ec5-4431-89d9-f6110d37d732)

**Comment by iArpanPatel** [comment]
Hi @PNg-HA, hope that you performed step 5 mentioned in the example CIFAR-10. This step should create 'user-ml-env-tf2.7.0' image locally. This local image will be used to spawn ml/user container when you execute 'run-sl' command. Please verify you are getting the image 'user-ml-env-tf2.7.0' locally upon performing step 5.

**Comment by PNg-HA** [comment]
My silly mistake. I forgot step 5. Thank you for your detailed help.
