### ISSUE TITLE
About Swarm images 

### ISSUE THREAD

**Issue by a1847979164** [HewlettPackard/swarm-learning#193]
https://[hub.myenterpriselicense.hpe.com/v2/hpe/swarm-learning/sn/manifests/2.0.0]，need to verify the login, where did the account password get from？

**Comment by iArpanPatel** [comment]
Hi @a1847979164, hope you are following the Swarm Learning installation steps from [here].(https://github.com/HewlettPackard/swarm-learning/blob/master/docs/Install/HPE_Swarm_Learning_installation.md)

**Comment by iArpanPatel** [comment]
Hi @a1847979164, you can switch to latest HPE Swarm Learning v2.1.0 version. Refer [v2.1.0 release announcement](https://github.com/HewlettPackard/swarm-learning/discussions/205).

**Comment by iArpanPatel** [comment]
@a1847979164 closing this issue, raise a new issue if you are facing any issue with v2.1.0
