### ISSUE TITLE
ERRO[0002] No identity issued in mnist-keras

### ISSUE THREAD

**Issue by JianhuanZeng** [HewlettPackard/swarm-learning#20]
(1) Problem describe:
![image](https://user-images.githubusercontent.com/37096176/124536995-9e9dfe80-de4b-11eb-923e-8c998918a619.png)
1.1 how to fix the error in the red box？
1.2 since it seem run successfully,  is it ok to run with this error? 
(2)  Setting: Debian GNU/Linux 10

**Comment by RadhakrishnaJ** [comment]
Hello,

1. Is not an issue. Multiple attempts are made to get identity. No action needed for this. 
2. For Setting, Need more details if you are asking any query here.

**Comment by RadhakrishnaJ** [comment]
As there is no comment from User and it seems there no issue here, this issue can be closed if needed requesting user to raise a new issue.
