### ISSUE TITLE
Error when Using HPE Passport email id

### ISSUE THREAD

**Issue by ljh14** [HewlettPackard/swarm-learning#21]
When I use the command 'docker login hub.myenterpriselicense.hpe.com -u <HPE-PASSPORT-EMAIL> -p hpe_eval', it failed.

WARNING! Using --password via the CLI is insecure. Use --password-stdin.

Error response from daemon: login attempt to https://hub.myenterpriselicense.hpe.com/v2/ failed with status: 401 Unauthorized

**Comment by RadhakrishnaJ** [comment]
Hello,

docker login hub.myenterpriselicense.hpe.com -u <HPE-PASSPORT-EMAIL> -p hpe_eval

In above command, HPE-PASSPORT-EMAIL refers to email id which you have used to register with MY HPE software center ( https://myenterpriselicense.hpe.com/cwp-ui/auth/login ) 

After replacing Yourmailid command translates like below - 
docker login hub.myenterpriselicense.hpe.com -u Yourmailid@mailservice.com -p hpe_eval

**Comment by ljh14** [comment]
Yes, I have replaced 'HPE-PASSPORT-EMAIL' with my email id, but it still did not work. I got status: 401 Unauthorized.

**Comment by RadhakrishnaJ** [comment]
From your response I am not sure you have registered with HPE software center.
Have you registered your mail id with MY HPE software center ( https://myenterpriselicense.hpe.com/cwp-ui/auth/login )? 

Also make sure you could able to login "https://myenterpriselicense.hpe.com/cwp-ui/auth/login" with same mail id.

**Comment by ljh14** [comment]
Thanks, I have solved the problem,
