### ISSUE TITLE
Error with Enrolled ID when custom MNIST example

### ISSUE THREAD

**Issue by PNg-HA** [HewlettPackard/swarm-learning#210]
#  Issue description
- issue description: When I configure the MNIST example so that each host can have 2 SL nodes, the SN nodes returns the error related to the enrolled ID.
- occurrence - consistent or rare: consistent
- error messages: SLBlackBoardObj : errUidNotMatchingWithEnroll:UID PASSED WITH CHECKIN IS NOT MATCHING WITH ENROLLED UID
- commands used for starting SN1: `./scripts/bin/run-sn -d --rm --name=sn1 \
--network=host-1-net --host-ip=${HOST_1_IP} \
--sentinel --sn-p2p-port=${SN_P2P_PORT} \
--sn-api-port=${SN_API_PORT} \
--key=workspace/mnist/cert/sn-1-key.pem \
--cert=workspace/mnist/cert/sn-1-cert.pem \
--capath=workspace/mnist/cert/ca/capath \
--apls-ip=${APLS_IP}`
- commands used for starting SN2: `./scripts/bin/run-sn -d --rm --name=sn2 \
--network=host-2-net --host-ip=${HOST_2_IP} \
--sentinel-ip=${SN_1_IP} --sn-p2p-port=${SN_P2P_PORT} \
--sn-api-port=${SN_API_PORT} --key=workspace/mnist/cert/sn-2-key.pem \
--cert=workspace/mnist/cert/sn-2-cert.pem \
--capath=workspace/mnist/cert/ca/capath \
--apls-ip=${APLS_IP}`
- commands used for starting SWOP1: `./scripts/bin/run-swop -d --name=swop1 --network=host-1-net \
--sn-ip=${SN_1_IP} --sn-api-port=${SN_API_PORT} \
--usr-dir=workspace/mnist/swop --profile-file-name=swop1_profile.yaml \
--key=workspace/mnist/cert/swop-1-key.pem \
--cert=workspace/mnist/cert/swop-1-cert.pem \
--capath=workspace/mnist/cert/ca/capath -e SWOP_KEEP_CONTAINERS=True -e http_proxy= -e https_proxy= \
--apls-ip=${APLS_IP}`
- command for SWOP2: `./scripts/bin/run-swop -d --name=swop2 --network=host-2-net \
--sn-ip=${SN_2_IP} --sn-api-port=${SN_API_PORT} \
--usr-dir=workspace/mnist/swop --profile-file-name=swop2_profile.yaml \
--key=workspace/mnist/cert/swop-2-key.pem \
--cert=workspace/mnist/cert/swop-2-cert.pem \
--capath=workspace/mnist/cert/ca/capath -e SWOP_KEEP_CONTAINERS=True -e http_proxy= -e https_proxy= \
--apls-ip=${APLS_IP}`
- command for SWCI in host 1: ` ./scripts/bin/run-swci --name=swci1 --network=host-1-net \
--usr-dir=workspace/mnist/swci --init-script-name=swci-init \
--key=workspace/mnist/cert/swci-1-key.pem \
--cert=workspace/mnist/cert/swci-1-cert.pem \
--capath=workspace/mnist/cert/ca/capath \
-e http_proxy= -e https_proxy= --apls-ip=${APLS_IP}`

- docker logs [APLS, SPIRE, SN, SL, SWCI]: 
- Host 1:
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/99674d39-e530-4a0f-a414-e06162dc068a)
- Host 2: 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/317fa5bd-f8e6-4b1c-b2c3-0670798ba220)

- APLS: 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/8f55f47f-21ed-4dca-b463-eb8ffb937019)

SN1: 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/841a7c89-b185-4b16-afb6-103619c0adad)

SN2:
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/e79e2287-4f00-4dec-b5dd-5dacc71b48cb)
- In the end there is a zip file that contains the changed file and container logs of both hosts.

# Swarm Learning Version: 2.1.0

# OS and ML Platform
- details of host OS: 2 Ubuntu server 20.04 LTS
- details of ML platform used: Keras (same file model as MNIST example)
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 2 machines, 4 SL, 2 SN nodes (2 SL per SN)

# Additional notes
- Are you running documented example without any modification? I have modified the example.
- Add any additional information about use case or any notes which supports for issue investigation: 
- Host 1 containers:
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/218d8f49-a5bd-4f16-8290-f5d0e9f177a2)
- Host 2 containers: 
![hosts2_containers](https://github.com/HewlettPackard/swarm-learning/assets/93396414/758691ba-6dde-4c68-b962-99963a0a3794)
- files changed: swci-init, swop1_profile (host 1), swop2_profile (host 2), swarm_mnist_task.yaml (both hosts)
[custom_mnist.zip](https://github.com/HewlettPackard/swarm-learning/files/13625589/custom_mnist.zip)

**Comment by htjain** [comment]
Did you restart sl/ml manually (docker start/restart)?

**Comment by PNg-HA** [comment]
No. I didn't touch sl/ml.

**Comment by iArpanPatel** [comment]
@PNg-HA, Thanks for providing all the logs and details about the issue. As I can see you have updated SWOP profile on both the hosts for adding additional SL nodes. 

Looking at the SL logs, each SL is exposing its file server port on 30305 which is default port, and it gets stuck in Merging stage. Refer about exposed port here: https://github.com/HewlettPackard/swarm-learning/blob/master/docs/Install/Exposed_port_numbers.md

To solve this provide different free ports in SWOP profile for each SL node per host. 
You need to update "slport: null" field in SWOP profile on both the hosts for each SL node. Instead of 'null' provide different port numbers. refer existing mnist example SWOP profile.

**Comment by htjain** [comment]
Strange, I have seen this issue when I restarted sl/ml manually.

**Comment by iArpanPatel** [comment]
Hi @PNg-HA, did you try suggested updates?

**Comment by PNg-HA** [comment]
> Hi @PNg-HA, did you try suggested updates?

Hi @iArpanPatel. Thank you for your detailed guide. I keep default slport (~) in one SL in each SWOP profile so one SL container in each host does not export the port (my lazy mistake when do not change all ports like your guide). I will change all ports and notify if there are still errors.

**Comment by PNg-HA** [comment]
I met a new error in the sentinel SN (host 1): 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/796cf669-d210-48ab-9c85-98b8e287a074)

I have updated slport in both hosts. In host 1, sl1 with port 16000, sl2 with port 17000. In host 2, sl3 with port 1600, sl4 with port 17000.
sn2 is normal: 
![image](https://github.com/HewlettPackard/swarm-learning/assets/93396414/c639bcde-5f6b-4d2f-997f-a9fc8fb6e35c)

**Comment by PNg-HA** [comment]
The new error is fixed in Swarm learning version 2.2.0. Thank you very much!
