### ISSUE TITLE
MNIST-Keras issue

### ISSUE THREAD

**Issue by ljh14** [HewlettPackard/swarm-learning#25]
When I try to run the mnist example, at the first step, "Create workspace and initialize Swarm Learning", running the command "./mnist-keras/bin/init-workspace -e $EXAMPLE -i $APLS_IP -d $WORKSPACE_DIR". It always shows the error that "Error response from daemon: network with name mnist-keras-net already exists
Failed to create docker network bridge."
However, I did not create the network with name mnist-keras-net before.

**Comment by RadhakrishnaJ** [comment]
It seems you have existing workspace. Follow “3. Delete workspace and remove Swarm Learning containers” as mentioned in example readme. Then you can able to run init-workspace.

**Comment by ljh14** [comment]
Yes, thanks for your suggestion! I have made it.
