### ISSUE TITLE
Model training doesn't begin in fraud-detection example

### ISSUE THREAD

**Issue by FrancescaFrattini** [HewlettPackard/swarm-learning#250]
# Issue description
- issue description:
- occurrence - consistent or rare: consistent
- error messages: SWCI task reaches maximum wait time for swarm_fd_task
- commands used for starting containers:  

`
sudo ./scripts/bin/run-sn -t --rm --name=sn1 --network=host-1-net --host-ip=${HOST_IP} --sentinel --sn-api-port=${SN_API_PORT}     
--key=workspace/fraud-detection/cert/sn-1-key.pem --cert=workspace/fraud-detection/cert/sn-1-cert.pem 
--capath=workspace/fraud-detection/cert/ca/capath --apls-ip=${APLS_IP}
`

`sudo ./scripts/bin/run-swop -t --rm --name=swop1 --network=host-1-net --usr-dir=workspace/fraud-detection/swop 
--profile-file-name=swop1_profile.yaml --sn-ip=${SN_IP} --sn-api-port=${SN_API_PORT} --key=workspace/fraud-detection/cert/swop-1-key.pem  --cert=workspace/fraud-detection/cert/swop-1-cert.pem --capath=workspace/fraud-detection/cert/ca/capath -e http_proxy= -e https_proxy= --apls-ip=${APLS_IP}
`

`
sudo ./scripts/bin/run-swci --name=swci1 --network=host-1-net --usr-dir=workspace/fraud-detection/swci --init-script-name=swci-init --key=workspace/fraud-detection/cert/swci-1-key.pem --cert=workspace/fraud-detection/cert/swci-1-cert.pem --capath=workspace/fraud-detection/cert/ca/capath  -e http_proxy= -e https_proxy= --apls-ip=${APLS_IP}
`

- docker logs [APLS, SPIRE, SN, SL, SWCI]: 

SWCI
```
SWCI:25 > ASSIGN TASK swarm_fd_task TO defaulttaskbb.taskdb.sml.hpe WITH 4 PEERS
  Task assigned to TaskRunner
SWCI:26 > SLEEP 30
SWCI:26 > Completed SLEEP for: 30 secs
SWCI:27 > PERFDATA defaultbb.cqdb.sml.hpe
  NAME : defaultbb.cqdb.sml.hpe
  NUM_NODES : 0
SWCI:28 > SLEEP 30
SWCI:28 > Completed SLEEP for: 30 secs
SWCI:29 > PERFDATA defaultbb.cqdb.sml.hpe
  NAME : defaultbb.cqdb.sml.hpe
  NUM_NODES : 0
SWCI:30 > SLEEP 30
SWCI:30 > Completed SLEEP for: 30 secs
SWCI:31 > PERFDATA defaultbb.cqdb.sml.hpe
  NAME : defaultbb.cqdb.sml.hpe
  NUM_NODES : 0
SWCI:32 > SLEEP 30
SWCI:32 > Completed SLEEP for: 30 secs
SWCI:33 > PERFDATA defaultbb.cqdb.sml.hpe
  NAME : defaultbb.cqdb.sml.hpe
  NUM_NODES : 0
SWCI:34 > SLEEP 30
SWCI:34 > Completed SLEEP for: 30 secs
SWCI:35 > PERFDATA defaultbb.cqdb.sml.hpe
  NAME : defaultbb.cqdb.sml.hpe
  NUM_NODES : 0
SWCI:36 > WAIT FOR TASKRUNNER defaulttaskbb.taskdb.sml.hpe
  WAITING FOR TASKRUNNER TO COMPLETE - Maximum wait time is : 120 mins
    #####################################################################################
    #####################################################################################
    #####################################################################################
    #####################################################################################
    #####################################################################################
    #####################################################################################
    other lines of "#"...
 
  WARNING - Maximum configured SWCI wait time is Over
SWCI:37 >
SWCI:37 > GET TASKRUNNER PEER STATUS defaulttaskbb.taskdb.sml.hpe 0
  NAME : demo
  SWOP_UID : 79bd725d-0cd6-4682-80f9-e51dc61bfa83
  OPERATION_ID : 9621560797185671369
  PEER_COUNT : 4
  UPDATE_TS : 2024-08-02 17:35:20
  SL_PEER_INDEX : 0
  SL_UID : NA
  SL_PEER_STATUS : RUNNING
  SL_PEER_STATUS_DESC : Created containers to match profile : 4
  SL_PEER_INDEX : 1
  SL_UID : NA
  SL_PEER_STATUS : RUNNING
  SL_PEER_STATUS_DESC : Created containers to match profile : 4
  SL_PEER_INDEX : 2
  SL_UID : NA
  SL_PEER_STATUS : RUNNING
  SL_PEER_STATUS_DESC : Created containers to match profile : 4
  SL_PEER_INDEX : 3
  SL_UID : NA
  SL_PEER_STATUS : RUNNING
  SL_PEER_STATUS_DESC : Created containers to match profile : 4
SWCI:38 >
```

SL node
```2024-08-02 17:35:36,134 : swarm.startSL : INFO : Creating Autopass License Provider
2024-08-02 17:35:42,421 : swarm.startSL : INFO : Creating license server
2024-08-02 17:35:42,423 : swarm.startSL : INFO : Setting license servers
2024-08-02 17:35:42,601 : swarm.startSL : INFO : Acquiring floating license 1100000378:1
2024-08-02 17:35:47,277 : swarm.startSL : INFO : Opening pipes to communicate with user container ...
2024-08-02T17:35:47.278661 /tmp/hpe-swarm/demo.0.0e2011de383cd612.request.pipe: pipe created
2024-08-02T17:35:47.279067 /tmp/hpe-swarm/demo.0.0e2011de383cd612.response.pipe: pipe created
```

# Swarm Learning Version:
- Find the docker tag of the Swarm images ( $ docker images | grep hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning )
- 2.2.0

# OS and ML Platform
- details of host OS: Ubuntu 22.04 LTS
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 1 machine with 4 SL nodes

# Quick Checklist: Respond [Yes/No]
/- If Multiple systems are used, can each system access every other system? 
- Is Password-less SSH configuration setup for all the systems?
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? no GPU
- Is the user id a member of the docker group? yes

# Additional notes
- Are you running documented example without any modification? yes, the fraud-detection
- Add any additional information about use case or any notes which supports for issue investigation: 

After starting the SWCI node, it runs the build task and then it gets stuck with the swarm task, printing only "#" until the maximum wait time is reached.

**Comment by pkbindhani** [comment]
Hi  @FrancescaFrattini 
I see the swci wait time ( 120mins ) was over,  before the run task is completed. 
 
  WARNING - Maximum configured SWCI wait time is Over
  
 So, I suspect  it is taking more than 2hrs to complete this run task.
 
I would advise you to use the environmental variable "SWCI_RUN_TASK_MAX_WAIT_TIME=<new value in minutes> while running run-swci script.
 
 For example:
$ sudo ./scripts/bin/run-swci --name=swci1 --network=host-1-net --usr-dir=workspace/fraud-detection/swci --init-script-name=swci-init --key=workspace/fraud-detection/cert/swci-1-key.pem --cert=workspace/fraud-detection/cert/swci-1-cert.pem --capath=workspace/fraud-detection/cert/ca/capath  -e http_proxy= -e https_proxy= --apls-ip=${APLS_IP}  -e SWCI_RUN_TASK_MAX_WAIT_TIME=240

// I hope this helps!

**Comment by FrancescaFrattini** [comment]
> Hi @FrancescaFrattini I see the swci wait time ( 120mins ) was over, before the run task is completed.
> 
> WARNING - Maximum configured SWCI wait time is Over
> 
> So, I suspect it is taking more than 2hrs to complete this run task.
> 
> I would advise you to use the environmental variable "SWCI_RUN_TASK_MAX_WAIT_TIME= while running run-swci script.
> 
> For example: $ sudo ./scripts/bin/run-swci --name=swci1 --network=host-1-net --usr-dir=workspace/fraud-detection/swci --init-script-name=swci-init --key=workspace/fraud-detection/cert/swci-1-key.pem --cert=workspace/fraud-detection/cert/swci-1-cert.pem --capath=workspace/fraud-detection/cert/ca/capath -e http_proxy= -e https_proxy= --apls-ip=${APLS_IP} -e SWCI_RUN_TASK_MAX_WAIT_TIME=240
> 
> // I hope this helps!

Hi, I've already tries setting the maximum wait time to 2000 mintues but it still goes out of time limits.
In the SL container logs (attached in the original post), it freezes after creating the comunication pipe and it seems like that it can't find the .py file with the model.
Looking inside each container, I can't find the /tmp/test/model containing the .py file: I believe that this is the real issue, but theorically the node should istantiate this folder on its own, I believe.

**Comment by pkbindhani** [comment]
I would be interested to see the SWOP log and content of swop profile. Could you please provide me the same ?

**Comment by FrancescaFrattini** [comment]
Here's the SWOP node log 

[swop_logs.txt](https://github.com/user-attachments/files/16570285/swop_logs.txt)

By the way I'm getting same issue as here - https://github.com/HewlettPackard/swarm-learning/issues/134, but the user just closed the issue without providing any solution

**Comment by FrancescaFrattini** [comment]
Little update: I've tried to run SWOP node with environmental variable SWOP_KEEP_CONTAINERS=true but still experiencing same behaviour as before.
Here I leave complete list of docker containers - I see that there are 4 __user-env-tf2.7.0-swop__ containers which have been exited, but I believe they're the result of the first build task

![containers](https://github.com/user-attachments/assets/d8d12073-178d-4e38-9ca6-a7d6868e2133)

**Comment by pkbindhani** [comment]
Thanks for this update..

I see 4 SL nodes  and 4 ML nodes were launched, however existed . Did you check the ML node logs ? what is it saying ?

You may send me the swarmLogCollector output to review.

**Comment by FrancescaFrattini** [comment]
Another update - I believe to have found the problem - my CPU doesn't support AVX instruction, and when ML nodes got instantiated they are immediately exited with the below warning.

![ml_log](https://github.com/user-attachments/assets/50681d19-53bc-4f7c-8a39-19fda9d6e2bb)

Is there any way for using Tensorflow without AVX?
