### ISSUE TITLE
can not connect to the License Server's management interface using a web browser

### ISSUE THREAD

**Issue by liang734** [HewlettPackard/swarm-learning#26]
**When I run the script "swarm-learning/bin/run-apls", it can run normally**(the part of the outputs:+ true
+ nc -z 127.0.0.1 5814
+ [[ 1 -eq 0 ]]
+ sleep 5
+ true
+ nc -z 127.0.0.1 5814
+ [[ 0 -eq 0 ]]
+ break
++ tr -d ' '
++ ps -C java -opid --no-header
+ aplsPID=18
+ echo 'Waiting for APLS pid 18 to terminate'
Waiting for APLS pid 18 to terminate
+ tail --pid=18 -f /dev/null),
 **but I cannot connect to the License Server's management interface using a web browser(google chrome、firefox).**
**the google chrome browser page content** (https://localhost:5814/autopass): The page is not working properly
![image](https://user-images.githubusercontent.com/54834215/125155249-109a7e80-e191-11eb-94b5-242b9779b846.png)

**Comment by ljh14** [comment]
Maybe this answer can help you:https://github.com/HewlettPackard/swarm-learning/issues/5.

**Comment by liang734** [comment]
thank you, but this answer did't have the problem like mine.

**Comment by RadhakrishnaJ** [comment]
Please confirm, are you running browser in the same system where the license server is running?

**Comment by ljh14** [comment]
I have met this problem before. And after I close the license server and restart it, the problem is solved.

**Comment by liang734** [comment]
**Do you mean restart run-apls script ? I tried, but still can't solve it.**
![image](https://user-images.githubusercontent.com/54834215/125246441-5fc4e880-e324-11eb-8160-17b15c3aaf34.png)

**Comment by ljh14** [comment]
It seems that you are using firefox. I try with firefox and google chrome, but only succeed with the latter. Maybe you could try with google chrome web browser?

**Comment by liang734** [comment]
**I try both and none of them can succeed.
the follow is chrome web browser:**
![image](https://user-images.githubusercontent.com/54834215/125253733-4cb61680-e32c-11eb-8cd7-0e7628a466de.png)

**Comment by ljh14** [comment]
Type in with the address "https://localhost:5814/"? I tried just now.

**Comment by liang734** [comment]
It works, thank you!
