### ISSUE TITLE
Cannot manually revoke a licence in use

### ISSUE THREAD

**Issue by maghsk** [HewlettPackard/swarm-learning#27]
Cannot manually revoke a Swarm Network Node ( 1100000380:1 ) license on APLS.

<img width="1410" alt="截屏2021-07-10 17 16 10" src="https://user-images.githubusercontent.com/16971372/125158274-88bd7000-e1a2-11eb-8861-888aa5aacf9d.png">

<img width="1418" alt="截屏2021-07-10 17 16 23" src="https://user-images.githubusercontent.com/16971372/125158275-8fe47e00-e1a2-11eb-8499-c48c3f101e7c.png">

But after 30 minutes of waiting, it will disappear automatically...

**Comment by RadhakrishnaJ** [comment]
No issue here, product has been designed to use SN node license the way you have observed.

**Comment by RadhakrishnaJ** [comment]
User observations matching with Licensing framework of Swarm Learning. Tokens are generated with 30 mins of expiry time. Closing this issue here. If any further discussion needed on this, please use Discussions forum.
