### ISSUE TITLE
connections between containers?

### ISSUE THREAD

**Issue by ljh14** [HewlettPackard/swarm-learning#28]
The warning "1. Ensure your network proxy settings are configured correctly and the containers are able to talk to each other." in running swarm learning. I wonder how to do this in detail. How can I know "the containers are able to talk to each other"? And "the network proxy settings are configured correctly"?
Thank you.

**Comment by RadhakrishnaJ** [comment]
This seems to be general docker containers requirements to work with. Please go through Docker networking and Container communication in general. 
If you have any specific issue with swarm setup then you can have this issue open. If issue is related to swarm, please provide context and some more details.

**Comment by RadhakrishnaJ** [comment]
Closing this issue, as there is no specific issue with Swarm. Requesting user to raise a new issue if needed.
