### ISSUE TITLE
Cannot download the AutoPass License Server from HPE

### ISSUE THREAD

**Issue by EdisonF666** [HewlettPackard/swarm-learning#29]
I cannot download the AutoPass License Server from the website HPE, the website always said it is a technical issue.

**Comment by RadhakrishnaJ** [comment]
Hello, 

May be License server has technical issue when you tried, please try again. I am seeing it is responding now. Could you please try once again?

**Comment by EdisonF666** [comment]
> Hello,
> 
> May be License server has technical issue when you tried, please try again. I am seeing it is responding now. Could you please try once again?

Hello,
I still cannot download the AutoPass License Server from the website HPE. If possible, could you please send it to me by email?

**Comment by RadhakrishnaJ** [comment]
> > Hello,
> > May be License server has technical issue when you tried, please try again. I am seeing it is responding now. Could you please try once again?
> 
> Hello,
> I still cannot download the AutoPass License Server from the website HPE. If possible, could you please send it to me by email?

License is user specific, it comes with validity. I can't share. It should work with any browser, please try once incognito mode in chrome.

**Comment by RadhakrishnaJ** [comment]
Requesting user to try again with different browsers and in different modes. It seems other users could able to download license.  Requesting user to raise a new issue or re-open this if needed.
