### ISSUE TITLE
How could I install the `swarm` library with `pip` or `conda`?

### ISSUE THREAD

**Issue by J-Zhangg** [HewlettPackard/swarm-learning#3]
With respect to the code in `from swarm import SwarmCallback` , how can I pip install the `swarm` library? Although I have searched everywhere for the link to install the library, I have not been able to find it.

Could you please solve my problem?

**Comment by saikatgithub** [comment]
Swarm learning comes pre-installed in the containers.
Please see the [Execute MNIST example](https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-keras) section on how to run simple example using Swarm Learning.
Also you can check [Adapting ML programs for Swarm Learning](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/ml_algorithm.md) section on how to transform Keras or PyTorch based model to Swarm Learning ML program by making a few simple changes to the model training code.
