### ISSUE TITLE
How to deploy SL in a bare-metal way rather than docker?

### ISSUE THREAD

**Issue by maghsk** [HewlettPackard/swarm-learning#33]
In many use cases, the non-root user has no access to docker. So is there any bare-metal way to deploy APLS server, spire-server, swarm learning, and swarm network node?

Thank you!

**Comment by RadhakrishnaJ** [comment]
Hello, 

Swarm Learning in Bare metal way is not supported. 

Non root user can access Docker by having user ID added to Docker group. Refer FAQ [Do you need sudo/root privileges to run Swarm Learning?](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#do-you-need-sudoroot-privileges-to-run-swarm-learning). 
Resources - 16. [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
Please try this approach.

**Comment by maghsk** [comment]
Hello @RadhakrishnaJ,

Thanks for your advice! I want to know the docker deployed by non-root users takes advantage of the NVIDIA GPU? It seems that installing the docker with GPU support needs root privilege.

**Comment by RadhakrishnaJ** [comment]
Hello, 

Swarm container provides capabilities to enable GPU use. With your user ID, you should have permissions to use GPU devices as well.  Please check with your local administrator to get device access.

**Comment by RadhakrishnaJ** [comment]
As there is no issue to address here, closing this issue. Requesting user to work with local administrator for any permissions.
