### ISSUE TITLE
How to run swarm learning in just different systems using a single licence?  

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#34]
I have successfully changed the test example for my application. 
The swarm learning in one system with two nodes works good for my application. 
Now I have three systems in the organization having different data in the same format. Can I run the whole setup in different systems?
What can I do since I don't have 10 systems as required for the MNIST example?
Can I run the sentinel node and the swarm learning node in a single system?

**Comment by RadhakrishnaJ** [comment]
As your setup is within organization, you don’t need to start second SN node. 

You can use one of the PC to run SPIRE, APLS and SN node. Start one SL in this PC.
Use other 2 PCs for SL only and attached to running SPIRE, APLS and SN in first PC.
As the first PC running most of the load, try to select first PC which has good performance out of 3 PCS.

Please follow setup as in swarm-learning/examples/mnist/ without second SN.

**Comment by RadhakrishnaJ** [comment]
Instructions provided to make setup with 3 PCs. This issue will be closed, requesting user to try and re-open/create issue if needed.
