### ISSUE TITLE
Need help for running mnist example

### ISSUE THREAD

**Issue by lanjinraol** [HewlettPackard/swarm-learning#35]
I try to run mnist example which has two Swarm Network nodes. I run the Sentinel Node sn-1 successfully.But it takes a long time to start GETH when I run the Swarm Network nodes sn-2. So I cannot start sn-2 successfully.
![126479522-2b1637cf-2f60-4f21-8c4f-95cf48a86565](https://user-images.githubusercontent.com/22259266/126725235-0eee049c-bc67-47dc-84a8-0dbd51251efb.png)

**Comment by RadhakrishnaJ** [comment]
Normally SN takes 2 to 3 minutes. With attached screenshot not seeing any error. Could you please provide more details, how long you waited and any other messages popped after that or is it stuck?

**Comment by lanjinraol** [comment]
I waited about 15 minutes and the last info was "Start GETH".  I am sure that it isn't stuck.

**Comment by RadhakrishnaJ** [comment]
1. Could you please share the docker logs for both the SN containers and SPIRE container as well?  

2. Please share machine configurations like 
a. OS version
b. All containers running in same node or multiple nodes
c. If multiple nodes, can each node access/reachable from the other nodes

Thanks.

**Comment by RadhakrishnaJ** [comment]
Closing this, requesting user to get back with docker logs if issue still exists.
