### ISSUE TITLE
Error when running example with tranfer learning model "resnet" 

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#36]
The error is below would like to get the solution
![error](https://user-images.githubusercontent.com/77096343/126637963-05a52225-26dd-41ec-b495-edd7b73f709e.png)

**Comment by RadhakrishnaJ** [comment]
> @RadhakrishnaJ can i get some support?

Hello, 
I need to spend sometime on this. Could you please describe your setup details and share only ML model file?

**Comment by oliversaldanha25** [comment]
Hello @RadhakrishnaJ,
Thank you so much for the fast reply.
I don't mind sharing the code and also the data which I am using. Could you please provide me with your email-id or any other way how I can explain the whole progress and the exact problem which I have been stuck from a long time.

**Comment by RadhakrishnaJ** [comment]
> Hello @RadhakrishnaJ,
> Thank you so much for the fast reply.
> I don't mind sharing the code and also the data which I am using. Could you please provide me with your email-id or any other way how I can explain the whole progress and the exact problem which I have been stuck from a long time.

No need to share data. For now share only ML model file. Please create Zip and drag file into comments area space. I tried same, in following zip you should able to see one test_file.py. 
[Test_Zip.zip](https://github.com/HewlettPackard/swarm-learning/files/6863783/Test_Zip.zip)

**Comment by oliversaldanha25** [comment]
This is the full model file
[model.zip](https://github.com/HewlettPackard/swarm-learning/files/6863853/model.zip)

**Comment by lanjinraol** [comment]
> @RadhakrishnaJ can i get some support?

You can try to stop all docker and re-install license.

**Comment by lanjinraol** [comment]
There may be some problems with Torch platform. I rewrite the implementation code with tensorflow framework and use Tensorflow platform instead.

**Comment by oliversaldanha25** [comment]
I have run the test example with the same docker container and it works fine.
I dont think its the platform issue. Its either the data format or the trasfer learning weights. how can we access the swarm.py file?

**Comment by oliversaldanha25** [comment]
I ran my data with your model and it works but still the problem for using transfer learning model does not work.
The main reason for this to happen is in the swarm learning callback 
swarm.SwarmCallback.loadModelWeightsFromDict could you please explain what is this Dict and how can we change the predefined weights for it.
If this cant be changed the the swarm learning can only be run for your specific light weight model which is not good.
@RadhakrishnaJ @lanjinraol can you please comment on this

**Comment by RadhakrishnaJ** [comment]
Swarm learning is not yet qualified to do Transfer learning.

**Comment by oliversaldanha25** [comment]
So we cant change any layer in the model? @RadhakrishnaJ . We have to just use your model which is 4 layers

**Comment by RadhakrishnaJ** [comment]
You can define your own model with any number of layers. When I said transfer learning, I mean model which includes mix of learning parameters (trainable and non trainable parameters) is not yet supported.

**Comment by oliversaldanha25** [comment]
Yes, i can only use a self-created model with multiple layers but cannot use the transfer learning model with  (trainable and non-trainable parameters). 
The issue was solved thanks for the support @RadhakrishnaJ and @lanjinraol
