### ISSUE TITLE
Try to run sl nodes on arm64v8 architecture.

### ISSUE THREAD

**Issue by ZzhKlaus** [HewlettPackard/swarm-learning#38]
I was planning to run some sl nodes on my Jetson nano to test some small datasets. But there is a compatibility problem, which says: 
"WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error"

I tried same command with my laptop, Ubuntu20, and it works. But Jetson nano with no luck. 
I wonder how can I solve it? Thanks a lot!

**Comment by RadhakrishnaJ** [comment]
Current Swarm docker images are built with images of platforms based out of linux/amd64. Running Swarm on ARM process is not yet supported.

**Comment by ZzhKlaus** [comment]
Thanks for the reply, I see.
