### ISSUE TITLE
Cannot run minist  example on a single system

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#40]
![Screenshot from 2021-08-04 10-41-45](https://user-images.githubusercontent.com/77096343/128152385-09478ce6-49d0-43ba-9d51-76a5f97fe18a.png)

I have attached the error. As suggested by @RadhakrishnaJ i tried to running APLS, Spire Server, Sentinel node in a single system and wanted to attach two other system later.
When i run the Sentinel node  i get this error

**Comment by oliversaldanha25** [comment]
Sorry that was the wrong screen shot Please find the error below
![Screenshot from 2021-08-04 10-41-45](https://user-images.githubusercontent.com/77096343/128151550-2db19bed-d401-47ec-9a6e-40466b672fe9.png)

**Comment by oliversaldanha25** [comment]
I have tried it on multiple systems but i get the same error.
The spire server is shown below
![spire-server](https://user-images.githubusercontent.com/77096343/128189646-3feeea58-ffd5-453e-ba57-0d59cb0853cf.png)

**Comment by oliversaldanha25** [comment]
There a a small mistake which i did i dint add the get token in the command
But this dint solve the issue, when i was running the sl-node in the same system i get this error.
Can i get the solution or in which direction i should work forward? @RadhakrishnaJ @sathya-SL 
![run-sl](https://user-images.githubusercontent.com/77096343/128209477-2a4195fa-ceae-447f-866b-e5235af8d722.png)

**Comment by RadhakrishnaJ** [comment]
We could able to see 2 issues with the commands. 
1. run-sn missing parameter -genJoinToken
2. run-sl has sn-fs-port instead of sl-fs-port

SPIRE and APLS and License should be setup before these commands.

Following is the info to confirm successful SN initialization.  
  swarm.blCnt : INFO : Starting SWARM-API-SERVER on port :30304 (As provided)
  This message does not come if APLS or SPIRE is not running correctly.

If issue still exists, please provide docker logs of APLS, SPIRE server, SN. If problem exists at SL, additionally provide SL docker log as well.

**Comment by oliversaldanha25** [comment]
This was the error which i was getting. Now i do not have that problem.
Now i have the sl-1 running. But when i am trying to run the sl-2 in the other system i am having the problem.
The first image is the full screen of my host system which i am running my APLS, SPIFFE, and SN1 and sl-1
![full_system_screen](https://user-images.githubusercontent.com/77096343/128333771-adc4f40d-4b07-4a19-99ad-9f075183932f.png)
The error which i am getting in the second and third system.
![second_system_error](https://user-images.githubusercontent.com/77096343/128334114-50a8ec91-cb33-4e11-acbc-42c3d2ed679d.png)
![third_system_error](https://user-images.githubusercontent.com/77096343/128334116-f9368f25-fa95-4657-a712-413111c23cf3.png)

**Comment by oliversaldanha25** [comment]
The command i used to start the sn-node is:
bash ./swarm-learning/bin/run-sn      --name=sn-1                  --host-ip=137.226.23.146         --sentinel-ip=137.226.23.146     --sn-p2p-port=10000          --sn-api-port=11000          --sn-fs-port=12000           --apls-ip 137.226.23.146          -serverAddress 137.226.23.146 -genJoinToken
The command i used to run sl-1 node is:
bash ./swarm-learning/bin/run-sl      --name=sl-1 --sl-platform=PYT    --host-ip=137.226.23.146         --sn-ip=137.226.23.146  --sn-api-port=11000          --sl-fs-port=16000  --data-dir=examples/mnist/app-data  --model-dir=examples/mnist/model  --model-program=mnist_pyt.py  --gpu=0        --apls-ip 137.226.23.146          -serverAddress 137.226.23.146 -genJoinToken
The command i used for sl-2 node in the second system is:
![second_system_error](https://user-images.githubusercontent.com/77096343/128345068-3bd702a5-49f4-4956-83e8-da6b43e1edd5.png)
@RadhakrishnaJ is this the problem of the port number because the error is saying port22: connection refused. I have not given port 22

**Comment by RadhakrishnaJ** [comment]
I don't see anything Swarm setup related here. This seems to be your local permissions issue.  Your machines should accessible from one other. 

Make sure following. 
1. Get access to Docker group in all the machines. 
2. Set up password less SSH connection.

**Comment by oliversaldanha25** [comment]
Thank you @RadhakrishnaJ  for the information. Can you please guide me to a link where can check how to get access to docker group in all machine and set up passwordless SSH connection? I am new to the field so it would be really helpful.

**Comment by RadhakrishnaJ** [comment]
> Thank you @RadhakrishnaJ for the information. Can you please guide me to a link where can check how to get access to docker group in all machine and set up passwordless SSH connection? I am new to the field so it would be really helpful.

We don't have any recommended instructions here.  
Refer FAQ on docker group [docker group](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#do-you-need-sudoroot-privileges-to-run-swarm-learning)
You can browse for "setup password less ssh" and try whatever works for you.

**Comment by oliversaldanha25** [comment]
Thanks for the information the issue is solved after

    Get access to Docker group in all the machines.
    Set up password less SSH connection.
