### ISSUE TITLE
MNIST-Keras cannot be deployed properly

### ISSUE THREAD

**Issue by 927-Charles** [HewlettPackard/swarm-learning#41]
I want to run the example of mnist-keras, However, the following error occurs when running Node 1. Here's how I did it.
Firstly, I use the swarm-learning/bin/run-apls script to start the License Server, and visit https://192.168.168.129:5814/autopass/login_input to install licenses.
![1](https://user-images.githubusercontent.com/60604946/128473548-3636e6f6-492b-4015-bd5d-8d4f7e238929.jpg)
Next, I run init-workspace script, and it’s working fine. I also try running a 'docker ps | grep swarm' and ensure all the swarm learning containers are running.
![2](https://user-images.githubusercontent.com/60604946/128473670-403e2d4e-5ea0-4a62-b5b5-20bd7af68f8d.jpg)
![3](https://user-images.githubusercontent.com/60604946/128473873-d0455b7f-6065-453b-a666-251231264f92.jpg)
![4](https://user-images.githubusercontent.com/60604946/128473895-3898f924-6acf-42e4-aa78-83cdfe5af886.jpg)
I'm new to the field. Can I get some advice and help to solve this ,thanks. @dgstangel @peholland

**Comment by oliversaldanha25** [comment]
Did you close the tab in which you run the APLS command?
Looks like the license server is not running.
Can you provide some more details?

**Comment by RadhakrishnaJ** [comment]
Yes, it seems APLS not running.

**Comment by 927-Charles** [comment]
I would like to ask whether the tab in which I run the APLS command refers to the url https://192.168.168.129:5814/autopass/login_input ? I didn't close this web page or any of the other terminals. 
Maybe there are some problems in my web，however i find something weird, after I install the license file, the License Usage page does not show these two licenses.Is this normal?
![1](https://user-images.githubusercontent.com/60604946/128507313-2a2a5cea-24c2-4a5a-8bc8-c6b8c676f3ad.png)
![2](https://user-images.githubusercontent.com/60604946/128507339-47c42649-9837-4896-b5a4-b1b26d37e87a.png)
In addition,For the environment variable APLS - IP, which IP should i use, 127.0.0.1 (https://127.0.0.1:5814/autopass/login_input) or 192.168.168.129 (https://192.168.168.129:5814Autopass/login_input)?
All the swarm learning containers are running as the figure bellow.
![3](https://user-images.githubusercontent.com/60604946/128507414-798cb1b2-35b4-4fc7-87d2-bed94b336c1f.png)
Last ,How can I confirm that APLS is running

**Comment by RadhakrishnaJ** [comment]
From above screen, APLS is running. Use complete IP to point APLS (no local host or 127...) . 
Your License Management console screen shows you have installed license properly. 

Lets restart setup.  

Follow delete work space command. 

Start again - 
Make sure APLS still running, License server shows License as installed. If not start APLS and install license. License Usage page refreshes only when Licenses are being used, in your attempt so far licenses are not used so it didn't show up. 
Run init-workspace, then run-sl command on both the nodes.

**Comment by 927-Charles** [comment]
i don't understand what exactly complete IP means, so I run the ifconfig command, could you tell me which one is correct, thanks for your timely reply
![1](https://user-images.githubusercontent.com/60604946/128528698-b2c71627-ce3f-491a-b3ba-8822cf7bc497.png)

**Comment by 927-Charles** [comment]
thank you, maybe i fix it
