### ISSUE TITLE
How to reduce the number of peer in the Swarm Network node

### ISSUE THREAD

**Issue by oliversaldanha25** [HewlettPackard/swarm-learning#44]
I have 2 systems and i want to have 2 SN nodes having one SL node each. 
I have changed the number of peers in the ML program but i cannot change the number of peers in the Swarm Network node.
![working](https://user-images.githubusercontent.com/77096343/129344046-e19027f3-b269-4350-ab63-78ace01c9930.png)

**Comment by RadhakrishnaJ** [comment]
Hello, Could you please provide Swarm callback API parameters from all the nodes?

**Comment by oliversaldanha25** [comment]
I am sorry for the late reply.

I will explain all the details in the post and the problem is still not resolved I tried many things. This is the final set for my project and would be really helpful if this problem is solved.
I have 3 systems with IP examples (172.1.1.1, 172.2.2.2, 172.3.3.3). I have set the min_peers = 3
The API license and the  Spire Server is run on the first system 172.1.1.1
I need 3 SN nodes with one SL node each(This is the requirement so I have to follow this)
The 1st SN node with is also the  Sentinel node is run on system 172.1.1.1 with the following command 
bash ./swarm-learning/bin/run-sn  \
    --name=sn-1              \
    --host-ip=172.1.1.1      \
    --sentinel-ip=172.1.1.1  \
    --sn-p2p-port=10000      \
    --sn-api-port=11000      \
    --sn-fs-port=12000       \
    --apls-ip 172.1.1.1     \
    -serverAddress 172.1.1. \
    -genJoinToken
The second SN node is run in the 2nd system with the IP 172.2.2.2 with the following command
bash ./swarm-learning/bin/run-sn  \
    --name=sn-2             \
    --host-ip=172.2.2.2      \
    --sentinel-ip=172.1.1.1  \
    --sn-p2p-port=13000      \
    --sn-api-port=14000      \
    --sn-fs-port=15000       \
    --apls-ip 172.1.1.1      \
    -serverAddress 172.1.1.1 \
    -genJoinToken
The third SN node is run in the 2nd system with the IP 172.3.3. with the following command
bash ./swarm-learning/bin/run-sn  \
    --name=sn-2             \
    --host-ip=172.2.2.2      \
    --sentinel-ip=172.1.1.1  \
    --sn-p2p-port=16000      \
    --sn-api-port=17000      \
    --sn-fs-port=18000       \
    --apls-ip 172.1.1.1      \
    -serverAddress 172.1.1.1 \
    -genJoinToken
After all, the three nodes are registered in the Sentinel node then
 I start the first SL node in system 1 with IP 172.1.1.1 with following command
bash ./swarm-learning/bin/run-sl        \
    --name=sl-1                         \
    --sl-platform=PYT                   \
    --host-ip=172.1.1.1                 \
    --sn-ip=172.1.1.1                   \
    --sn-api-port=11000                 \
    --sl-fs-port=19000                  \
    --data-dir=examples/mnist/app-data  \
    --model-dir=examples/mnist/model    \
    --model-program=mnist_pyt.py        \
    --gpu=0                             \
    --apls-ip 172.1.1.1                 \
    -serverAddress 172.1.1.1            \
    -genJoinToken

This output is shown below 
![system1](https://user-images.githubusercontent.com/77096343/129935629-052207a4-d79c-41ad-b9e1-d886168e3001.png)

 After this I start the second SL node in system 1 with IP 172.2.2.2 with following command
 bash ./swarm-learning/bin/run-sl        \
    --name=sl-1                         \
    --sl-platform=PYT                   \
    --host-ip=172.2.2.2                 \
    --sn-ip=172.2.2.2                   \
    --sn-api-port=14000                 \
    --sl-fs-port=20000                  \
    --data-dir=examples/mnist/app-data  \
    --model-dir=examples/mnist/model    \
    --model-program=mnist_pyt.py        \
    --gpu=0                             \
    --apls-ip 172.1.1.1                 \
    -serverAddress 172.1.1.1            \
    -genJoinToken

This output is shown below 
![system2](https://user-images.githubusercontent.com/77096343/129935659-951ad47e-fd07-4213-8ce5-994a75268d0c.png)

 After this I start the third SL node in system 1 with IP 172.3.3.3 with following command
 bash ./swarm-learning/bin/run-sl        \
    --name=sl-1                         \
    --sl-platform=PYT                   \
    --host-ip=172.3.3.3                \
    --sn-ip=172.3.3.3                   \
    --sn-api-port=17000                 \
    --sl-fs-port=21000                  \
    --data-dir=examples/mnist/app-data  \
    --model-dir=examples/mnist/model    \
    --model-program=mnist_pyt.py        \
    --gpu=0                             \
    --apls-ip 172.1.1.1                 \
    -serverAddress 172.1.1.1            \
    -genJoinToken

This is the output
![system3](https://user-images.githubusercontent.com/77096343/129934952-7c9be1fc-69a8-4e91-9099-e1a93f8f83d3.png)


Please let me know if any more information is needed. 
@RadhakrishnaJ I would really appreciate it if I could get to know what I am doing wrong.
All the comments made by @RadhakrishnaJ were very useful for my project.
I would really appreciate any support from @sathya-SL or any other members.

**Comment by oliversaldanha25** [comment]
I know i am doing something basic very wrong can you please comment @RadhakrishnaJ.
When ever i want to use the use the second SN node it is not working.
I tried to run the SWCI i get the following error
![swic](https://user-images.githubusercontent.com/77096343/130049879-45c5b7b4-ed38-4241-b269-42a8a8314540.png)

**Comment by RadhakrishnaJ** [comment]
> I know i am doing something basic very wrong can you please comment @RadhakrishnaJ.
> When ever i want to use the use the second SN node it is not working.
> I tried to run the SWCI i get the following error
> ![swic](https://user-images.githubusercontent.com/77096343/130049879-45c5b7b4-ed38-4241-b269-42a8a8314540.png)

you need to pass location of spire and apls server to run swci

**Comment by RadhakrishnaJ** [comment]
> I am sorry for the late reply.
> 
> I will explain all the details in the post and the problem is still not resolved I tried many things. This is the final set for my project and would be really helpful if this problem is solved.
> I have 3 systems with IP examples (172.1.1.1, 172.2.2.2, 172.3.3.3). I have set the min_peers = 3
> The API license and the Spire Server is run on the first system 172.1.1.1
> I need 3 SN nodes with one SL node each(This is the requirement so I have to follow this)
> The 1st SN node with is also the Sentinel node is run on system 172.1.1.1 with the following command
> bash ./swarm-learning/bin/run-sn
> --name=sn-1
> --host-ip=172.1.1.1
> --sentinel-ip=172.1.1.1
> --sn-p2p-port=10000
> --sn-api-port=11000
> --sn-fs-port=12000
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.
> -genJoinToken
> The second SN node is run in the 2nd system with the IP 172.2.2.2 with the following command
> bash ./swarm-learning/bin/run-sn
> --name=sn-2
> --host-ip=172.2.2.2
> --sentinel-ip=172.1.1.1
> --sn-p2p-port=13000
> --sn-api-port=14000
> --sn-fs-port=15000
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.1
> -genJoinToken
> The third SN node is run in the 2nd system with the IP 172.3.3. with the following command
> bash ./swarm-learning/bin/run-sn
> --name=sn-2
> --host-ip=172.2.2.2
> --sentinel-ip=172.1.1.1
> --sn-p2p-port=16000
> --sn-api-port=17000
> --sn-fs-port=18000
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.1
> -genJoinToken
> After all, the three nodes are registered in the Sentinel node then
> I start the first SL node in system 1 with IP 172.1.1.1 with following command
> bash ./swarm-learning/bin/run-sl
> --name=sl-1
> --sl-platform=PYT
> --host-ip=172.1.1.1
> --sn-ip=172.1.1.1
> --sn-api-port=11000
> --sl-fs-port=19000
> --data-dir=examples/mnist/app-data
> --model-dir=examples/mnist/model
> --model-program=mnist_pyt.py
> --gpu=0
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.1
> -genJoinToken
> 
> This output is shown below
> ![system1](https://user-images.githubusercontent.com/77096343/129935629-052207a4-d79c-41ad-b9e1-d886168e3001.png)
> 
> After this I start the second SL node in system 1 with IP 172.2.2.2 with following command
> bash ./swarm-learning/bin/run-sl
> --name=sl-1
> --sl-platform=PYT
> --host-ip=172.2.2.2
> --sn-ip=172.2.2.2
> --sn-api-port=14000
> --sl-fs-port=20000
> --data-dir=examples/mnist/app-data
> --model-dir=examples/mnist/model
> --model-program=mnist_pyt.py
> --gpu=0
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.1
> -genJoinToken
> 
> This output is shown below
> ![system2](https://user-images.githubusercontent.com/77096343/129935659-951ad47e-fd07-4213-8ce5-994a75268d0c.png)
> 
> After this I start the third SL node in system 1 with IP 172.3.3.3 with following command
> bash ./swarm-learning/bin/run-sl
> --name=sl-1
> --sl-platform=PYT
> --host-ip=172.3.3.3
> --sn-ip=172.3.3.3
> --sn-api-port=17000
> --sl-fs-port=21000
> --data-dir=examples/mnist/app-data
> --model-dir=examples/mnist/model
> --model-program=mnist_pyt.py
> --gpu=0
> --apls-ip 172.1.1.1
> -serverAddress 172.1.1.1
> -genJoinToken
> 
> This is the output
> ![system3](https://user-images.githubusercontent.com/77096343/129934952-7c9be1fc-69a8-4e91-9099-e1a93f8f83d3.png)
> 
> Please let me know if any more information is needed.
> @RadhakrishnaJ I would really appreciate it if I could get to know what I am doing wrong.
> All the comments made by @RadhakrishnaJ were very useful for my project.
> I would really appreciate any support from @sathya-SL or any other members.



As per commands for third SN , host ip is set to 2nd system. Is this type error here? are you missed same while running command?
You need to reset learning process, need to follow RESET command (as in 3rd section of examples) to match with your setup . Make sure you have ML model and callback parameters same in all the nodes. 
or
stop all containers, re-start fresh with ML code and callback same in all nodes. 

Thanks for your appreciation. 
One request, you need to tag anyone in response. We will try to reply ASAP.

**Comment by oliversaldanha25** [comment]
The SN host ip is the typo error. Sorry for tagging you for response.
I have the ML model and parameters same in all the nodes. I still dint understand the problem.

**Comment by oliversaldanha25** [comment]
What is the RESET command you are referring to i have not fond this command in the examples. Can i use this command to change the number of SN nodes?

**Comment by RadhakrishnaJ** [comment]
> What is the RESET command you are referring to i have not fond this command in the examples. Can i use this command to change the number of SN nodes?

Why do you want to reduce SN nodes now? I understood you were trying 3 SN nodes with 1 SL node attached to each SN.  If you want less number of SN nodes then you don't need to run SN command in that machine.  You can have one machine for SL node only, attach it to any running SN node while running SL.

**Comment by oliversaldanha25** [comment]
I dont need to reduce the SN node. I just need the system to know that i have 3 SN nodes which are having one SL node attached to each. I want the 3 systems to merge the learning after each epoch.
Could you please tell me what should i keep my min_peers value in the ML program?

**Comment by RadhakrishnaJ** [comment]
> I dont need to reduce the SN node. I just need the system to know that i have 3 SN nodes which are having one SL node attached to each. I want the 3 systems to merge the learning after each epoch.
> Could you please tell me what should i keep my min_peers value in the ML program?

As when you run SN command, mentioning sentinal node it creates SN network chain. No need to do any explicit set on minimum SN nodes. Minimum SL nodes are needed to start merge process. Based on your use case you decide on how many SL nodes you want to set it as min peers, min peers mentioned in swarmcallback is the min SL nodes required for swarm merge process.

**Comment by oliversaldanha25** [comment]
The information provided was really helpful. I have successfully achieved what I wanted to achieve.

**Comment by oliversaldanha25** [comment]
> > I know i am doing something basic very wrong can you please comment @RadhakrishnaJ.
> > When ever i want to use the use the second SN node it is not working.
> > I tried to run the SWCI i get the following error
> > ![swic](https://user-images.githubusercontent.com/77096343/130049879-45c5b7b4-ed38-4241-b269-42a8a8314540.png)
> 
> you need to pass location of spire and apls server to run swci

I was unable to start the run swci with the command
run-swci spire 172.1.1.1 apls server 172.1.1.1
