### ISSUE TITLE
Ask for help - License server related.

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#5]
Licenses for running the Swarm Learning package should be installed on the License Server. After completing the product installation, start the License Server container using the scripts/bin/run-apls script. The parameters for this script are described in the Running Swarm Learning section. Then, connect to the License Server's management interface using a web browser. This site can be reached using the link,  https://<IP-address-or-FQDN-of-host-running-License-Server-container>:5814/autopass. The default username is, "admin", and the password, "password".

How to get  IP-address-or-FQDN-of-host-running-License-Server-container?

Thanks

**Comment by suresh-ls** [comment]
Hope you have started the license server container on a linux host machine by using the "run-apls" script ?  

One can find the IP address of the host machine, by running the "ifconfig" command. Please refer its man page for details.

If the IP address of that host machine, say for eg is 192.168.10.15, then by using  https://192.168.10.15:5814/autopass from your browser we can access the management interface  (Assuming the License Server has been started with its default port)

**Comment by difan0224** [comment]
Hello, I use Linux, I would like to know what is right output of "run-apls" script? And where you download the License Server?

my output afyer run-apsl
+++ dirname /opt/autopass/AutopassLicenseServer/bin/entrypoint
++ realpath /opt/autopass/AutopassLicenseServer/bin/..
+ aplsRootDir=/opt/autopass/AutopassLicenseServer
+ aplsInstallDir='/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server'
+ aplsBinDir='/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin'
+ '/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/startup.sh'
Using CATALINA_BASE:   /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server
Using CATALINA_HOME_HPAPLS:   /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server
Using CATALINA_TMPDIR: /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/temp
Using JRE_HOME:        /opt/autopass/AutopassLicenseServer/jre
Using CLASSPATH:       /opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/bootstrap.jar:/opt/autopass/AutopassLicenseServer/HP AutoPass License Server/HP AutoPass License Server/bin/tomcat-juli.jar
Tomcat started.
+ true
+ nc -z 127.0.0.1 5814
+ [[ 1 -eq 0 ]]
+ sleep 5
+ true
+ nc -z 127.0.0.1 5814
+ [[ 0 -eq 0 ]]
+ break
++ ps -C java -opid --no-header
++ tr -d ' '
+ aplsPID=17
+ echo 'Waiting for APLS pid 17 to terminate'
Waiting for APLS pid 17 to terminate

Is this correct?
Thanks.

**Comment by suresh-ls** [comment]
Hi,

The above output is correct.  The license server is running.  I am assuming you have started it on the default port (5814) and not changed it.

1) Hope you have downloaded the license file from the HPE MSC page ?  Please do so, if its not done.

2)  If you can run a browser on the host machine where you ran the "run-apls" script,  You can now connect to the License server using https://localhost:5814/autopass  from a browser on the host machine and install the license downloaded in Step 1.

(OR)

3) Else, if the host machine is accessible from your laptop/desktop, then you can access by using https://<IP addr / FQDN addr >:5814/autopass from your laptop browser and install the license downloaded in Step 1.

   else, 
   
   you can setup SSH port forwarding first and then access it using as mentioned in Step 2.

**Comment by difan0224** [comment]
Hi,

Is the license file HPE-SWARM_90_9999_34289026.dat? Is there any instruction how to set up this? I did not find this on github or HPE AutoPass License Server User Guide.pdf.

I use a ssh to connect my gpu server to install this environment. Will the port still be 5814? And in this case, I should use this https://<IP addr / FQDN addr of host machine>:5814/autopass, correct?

Thanks.

**Comment by suresh-ls** [comment]
Yes, that is the license file..   You will find instructions for setting the license under chapter "HPE AutoPass License Server License Management" in HPE AutoPass License Server User Guide.pdf

Its mentioned in github. Under "Getting  Started" ->"Download and setup docker images and evaluation licenses" section of the main README!

Since you have not given a different port, then it should use the default 5814 in your case..    Use the URL depending on whether your GPU server is reachable from your laptop browser (as mentioned in my previous reply.)

**Comment by difan0224** [comment]
Hello,

Thanks.
I notice this, but I use command line for install software. Could you please tell me how can I install license with command line?
Thanks.
![image](https://user-images.githubusercontent.com/38574065/123254405-79041300-d4a3-11eb-80a9-dc717b6cea53.png)

**Comment by suresh-ls** [comment]
There is no command line..  We need to use the browser.

**Comment by difan0224** [comment]
Hello,

Thanks. I can install it now. I setup SSH port forwarding first and then access https://localhost:5814/autopass from my laptop browser and install the license. By the way, will I install every time I start the license server?

The other issue is I want to run mnist-keras. I follow this https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-keras. After first step that I get ws-mnist-keras folder, and I try to run 
./mnist-keras/bin/run-sl --name $TRAINING_NODE-sl --network $EXAMPLE-net --host-ip $TRAINING_NODE-sl --sn-ip node-sn -e MAX_EPOCHS=5 --apls-ip $APLS_IP --serverAddress node-spire -genJoinToken --data-dir $WORKSPACE_DIR/ws-$EXAMPLE/$TRAINING_NODE/app-data --model-dir $WORKSPACE_DIR/ws-$EXAMPLE/$TRAINING_NODE/model --model-program mnist_tf.py --sl-platform TF

but it shows like this 
WARN[0000] Current umask 0022 is too permissive; setting umask 0027 
INFO[0000] Starting agent with data directory: "/spire/data/agent" 
INFO[0000] Plugin loaded                                 built-in_plugin=false plugin_name=swarm plugin_services="[]" plugin_type=WorkloadAttestor subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=memory plugin_services="[]" plugin_type=KeyManager subsystem_name=catalog
INFO[0000] Plugin loaded                                 built-in_plugin=true plugin_name=join_token plugin_services="[]" plugin_type=NodeAttestor subsystem_name=catalog
INFO[0000] Bundle is not found                           subsystem_name=attestor
INFO[0000] SVID is not found. Starting node attestation  subsystem_name=attestor
2021-06-25 04:59:01,782 : swarm.mlApp : INFO : Creating Autopass License Provider
Jun 25, 2021 4:59:01 AM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/platform/swarmml/autopassj/lib/jaxb-impl-2.1.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-06-25 04:59:02,395 : swarm.mlApp : INFO : Creating license server
2021-06-25 04:59:02,396 : swarm.mlApp : INFO : Setting license servers
2021-06-25 04:59:02,405 : swarm.mlApp : INFO : Acquiring floating license 1100000378:1
2021-06-25 04:59:02,966 : swarm.mlApp : ERROR : acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "start_swarm_ml.py", line 97, in start_swarm_ml.main
  File "manager.py", line 157, in manager.acquireLicense
  File "alp.py", line 321, in provider.autopass.alp.AutopassLicenseProvider.acquireLicense
  File "swarmutils.py", line 619, in swarmutils.swarmlogger.emitError
RuntimeError: acquireLicense: 304: The request for tokens with capacity 1 is not available to issue for feature : 1100000378:1
2021/06/25 04:59:03 exit status 1

What could be the problem?
Thanks

**Comment by suresh-ls** [comment]
I am closing this issue as the license server works fine and you are able to install the license.

Opening a new issue for the mnist-keras help for easier tracking. Also would help others searching here :-)

**Comment by ljh14** [comment]
What's the difference between the IP address of docker and the IP address of wlp3s0？And which one should I choose as the host IP address and Sentinel node IP address?
