### ISSUE TITLE
Mail configuration and server configuration(in Configuration page)

### ISSUE THREAD

**Issue by semi-hollow** [HewlettPackard/swarm-learning#53]
I have some problems setting the mail server in the panel page.
<img width="810" alt="Screen Shot 2021-09-20 at 17 42 07" src="https://user-images.githubusercontent.com/64388497/133982804-9ea3636a-63b2-4848-933b-396df6cdeace.png">

Firstly I want to make sure if I can use my google mail as the admin email.
If this is permitted, then what is the port?

<img width="740" alt="Screen Shot 2021-09-20 at 17 32 36" src="https://user-images.githubusercontent.com/64388497/133981756-4f6b582a-b795-45be-9d7b-fd896d5f576a.png">
From this picture I know that the SSL port for gmail is 465, so should I use the 465 here?
And should I fill the mail server with "smtp.gmail.com"？

With these information, I can only get "Sending Email failed. Please enter the correct mail server,port or admin email
"

**Comment by semi-hollow** [comment]
In the server configuration, I fill it with my ipv4 in ubuntu virtual machine,but
<img width="435" alt="Screen Shot 2021-09-20 at 17 39 48" src="https://user-images.githubusercontent.com/64388497/133982532-421b2640-2645-44de-ac07-f6535f637d7e.png">
if this is right and necessary? 
<img width="613" alt="Screen Shot 2021-09-20 at 17 41 01" src="https://user-images.githubusercontent.com/64388497/133982670-3ff754de-fc6d-4796-a4bd-4d9334f3f3cd.png">

**Comment by RadhakrishnaJ** [comment]
For mail configuration, you should specify the details provided by your organization. Please refer page 20 [Main configuration tab](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/HPE%20AutoPass%20License%20Server%20User%20Guide.pdf) of the APLS guide and work with your admin to set up mail configuration.

Mail configuration is not required to run APLS, you can still use all Swarm Learning components without setting up mail configuration.

**Comment by semi-hollow** [comment]
> For mail configuration, you should specify the details provided by your organization. Please refer page 20 [Main configuration tab](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/HPE%20AutoPass%20License%20Server%20User%20Guide.pdf) of the APLS guide and work with your admin to set up mail configuration.
> 
> Mail configuration is not required to run APLS, you can still use all Swarm Learning components without setting up mail configuration.

Thank you! but I'm confused why this problem would happen every time I logged into the apls web page and want to run the run-sl script? 

"AutoPass License Server is currently running in "Standalone" mode. It can also be configured to run in "Redundant" mode.
Switching from Standalone to Redundant mode and vice versa will result in losing data and requires reconfiguration of AutoPass License Server.
Click here to continue in Standalone mode or change to "Redundancy" mode before proceeding with other configurations."


I have logged into the apls web page, without finishing the mail server configuration, and I have installed the license, but soon my account password will be set to default, and the information I filled, the license I installed will disapper, then when i want to run the run-sl, there would be error 6002, because my installed license would not exist any more at that time .

**Comment by RadhakrishnaJ** [comment]
> > For mail configuration, you should specify the details provided by your organization. Please refer page 20 [Main configuration tab](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/HPE%20AutoPass%20License%20Server%20User%20Guide.pdf) of the APLS guide and work with your admin to set up mail configuration.
> > Mail configuration is not required to run APLS, you can still use all Swarm Learning components without setting up mail configuration.
> 
> Thank you! but I'm confused why this problem would happen every time I logged into the apls web page and want to run the run-sl script?
> 
> "AutoPass License Server is currently running in "Standalone" mode. It can also be configured to run in "Redundant" mode.
> Switching from Standalone to Redundant mode and vice versa will result in losing data and requires reconfiguration of AutoPass License Server.
> Click here to continue in Standalone mode or change to "Redundancy" mode before proceeding with other configurations."
> 
> I have logged into the apls web page, without finishing the mail server configuration, and I have installed the license, but soon my account password will be set to default, and the information I filled, the license I installed will disapper, then when i want to run the run-sl, there would be error 6002, because my installed license would not exist any more at that time .

Please refer [Troubleshooting](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/Troubleshooting.md#troubleshooting) for this error resolution. 
APLS installed licenses and password will be valid as long as apls container is live.
