### ISSUE TITLE
Problems in "Starting Swarm Network node"

### ISSUE THREAD

**Issue by DoLNw** [HewlettPackard/swarm-learning#56]
**When I run command "./mnist-keras/bin/init-workspace -e $EXAMPLE -i $APLS_IP -d $WORKSPACE_DIR", I got the following result:**

Parameters -
mnist-keras  2  192.168.1.105  /Users/jc/Downloads/swraming-learning代码综合/swarm-learning-master/examples  /Users/jc/Downloads/swraming-learning代码综合/swarm-learning-master/examples
/Users/jc/Downloads/swraming-learning代码综合/swarm-learning-master/examples/ws-mnist-keras/node1 directory is created and updated.
/Users/jc/Downloads/swraming-learning代码综合/swarm-learning-master/examples/ws-mnist-keras/node2 directory is created and updated.
Data and model files are generated for each node inside the workspace /Users/jc/Downloads/swraming-learning代码综合/swarm-learning-master/examples/ws-mnist-keras.
Creating docker network bridge mnist-keras-net.
ec330b91da612d42c7c86355d005e08b55def528f0e5e6d93048bf3966d816fa
Starting spire server
051b9879225775907f7048f12be49a3976582a20982c83d14a4526dbf1f9ea9d
Waiting for spire server to initialize
**Starting Swarm Network node
hostname: illegal option -- I
usage: hostname [-fs] [name-of-host]
Error opening Certificate -
4584148652:error:02FFF002:system library:func(4095):No such file or directory:/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/crypto/bio/bss_file.c:255:fopen('-', 'r')
4584148652:error:20FFF002:BIO routines:CRYPTO_internal:system lib:/System/Volumes/Data/SWE/macOS/BuildRoots/2288acc43c/Library/Caches/com.apple.xbs/Sources/libressl/libressl-56.60.2/libressl-2.8/crypto/bio/bss_file.c:257:
unable to load certificate
Error: spiffeid: invalid scheme
run-sn: cannot generate join token
Swarm Network node failed to start.**

**there are some errors in "Starting Swarm Network node", both in macOS 11.3 and Centos 7.3, how can I solve it ? thank you!**

**Comment by DoLNw** [comment]
I realize that the command "sudo  docker exec node-spire '/spire/bin/spire-server' bundle show | openssl x509 -in - -text" results that error, but I can't resolve it, can you give me some suggestions?

**Comment by oliversaldanha25** [comment]
@DoLNw . From the first look it looks like your license is not activated. Just close the HPE website. Run the 'stop-swarm --all' command from the bin.
Then start the license server again with 'run-apls' command and then go to the server and activate the key with .dat file.
Then give the inite-workspace command this should solve the problem.

**Comment by RadhakrishnaJ** [comment]
As there is no issue with Swarm, closing this issue now. Requesting user to start a new issue if any support needed.
