### ISSUE TITLE
Problem with get HPE docker 

### ISSUE THREAD

**Issue by ljh14** [HewlettPackard/swarm-learning#6]
Hello, I cannot access the HPE docker registry (http://hub.myenterpriselicense.hpe.com/. Is there any other way to get the code of implementing the smart contract?

**Comment by imtypist** [comment]
Me, too

**Comment by suresh-ls** [comment]
We need to download the images only from docker.

Hope you have created an account in https://myenterpriselicense.hpe.com first and using that login to docker ?

The docker registry works fine and i checked it just now..
$ date;   docker login hub.myenterpriselicense.hpe.com -u <sample@gmail.com -p hpe_eval

Sunday 27 June 2021 09:25:30 AM IST
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/swarm/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Login Succeeded

**Comment by suresh-ls** [comment]
Hope it worked?  I am closing this issue. please reopen the issue, if it didn't (with more details of the exact error)

**Comment by ljh14** [comment]
Thanks , I tried with your way. But it said that I was still unauthrized, error code 401. However, I have logged up for the HPE account esveral days ago.
