### ISSUE TITLE
Can not pull docker images after login succeed

### ISSUE THREAD

**Issue by semi-hollow** [HewlettPackard/swarm-learning#61]
I create my email account in  My HPE Software Center (MSC), and use this to login in docker:
![image](https://user-images.githubusercontent.com/64388497/138906287-ba193c47-e66d-44bc-b5b0-f1d1f1e4d623.png)

and I have enabled docker content trust.

But when I run this:
![image](https://user-images.githubusercontent.com/64388497/138906438-dc808a0d-96a4-403f-91f0-faef1ea6a598.png)
it was like this:
![image](https://user-images.githubusercontent.com/64388497/138906496-8ddd1488-7255-426f-bde0-53b104a2416a.png)

and I can not pull docker images, either.
![image](https://user-images.githubusercontent.com/64388497/138906673-5ded2f9d-fde0-450a-87e9-aaeb33c85fc1.png)

**Comment by RadhakrishnaJ** [comment]
Hello, 
License .DAT file is needed later once images are in available. 

I have tried pulling images today, all of them are pulled properly without any issue. 
Docker login does not require sudo in command. 

If still does not work, please see if you can register with another mail id and try.

**Comment by RadhakrishnaJ** [comment]
Closing this issue, requesting user to raise a new issue if needed.
