### ISSUE TITLE
Issue with certificates and token generation

### ISSUE THREAD

**Issue by pisocrob** [HewlettPackard/swarm-learning#63]
#  Issue description
- issue description: When running init_workspace for the mnist pytorch example two errors occur when the script attempts to start the Swam Network node. The first is an illegal option caused by hostname, it appears to be due to the hostname command on macOS not having an -I flag.
- 
![image](https://user-images.githubusercontent.com/6840420/139868204-dfa71fa8-2d98-48be-b274-e53904298a31.png)

The second occurs right after the first, it seems to be that a specific version of libressl is expected, although even with libressl installed, the expecte directory does not exist.

![image](https://user-images.githubusercontent.com/6840420/139871948-4a19a80e-f731-45f2-98f6-0d871329a103.png)

I am running `./mnist-pytorch/bin/init-workspace -e $EXAMPLE -i $APLS_IP -d $WORKSPACE_DIR` with environmental variable set as follows:
`export APLS_IP=https://xxxxxxxxxxxx.ngrok.io`
`export EXAMPLE=mnist-pytorch`
`export WORKSPACE_DIR=$PWD`

Spire container logs show no errors, there are not logs for Swarm Network node container as it does not start.

# OS and ML Platform
- details of host OS: macOS Monterey 12.0.1 
- details of ML platform used: N/A
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): As defined by mnist-pytorch example.

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses? Yes
- If Multiple systems are used, can each system access every other system? N/A
- Is Password-less SSH configuration setup for all the systems? N/A
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? N/A
- Is the user id a member of the docker group? N/A

# Additional notes
- Are you running documented example without any modification? Yes
- Add any additional information about use case or any notes which supports for issue investigation: Had a few minor issues with missing commands such as `shopt`. These were overcome by switching for zshell to bash and installing coreutils via Homebrew.

Thank you for your time, any fixes or advice would be greatly appreciated :)

**Comment by RadhakrishnaJ** [comment]
Swarm is qualified to work with Ubuntu OS only. Please refer below issue for more details.
[Issue 56](https://github.com/HewlettPackard/swarm-learning/issues/56)

**Comment by RadhakrishnaJ** [comment]
Closing this issue as this issue reported outside swarm qualified OS.
