### ISSUE TITLE
About INSTALLMENT & DEPLOYMENT

### ISSUE THREAD

**Issue by daishu-li** [HewlettPackard/swarm-learning#65]
Dear RadhakrishnaJ,

As researchers in distributed computing, we are keen for your team to give instructional videos on installation and deployment.
Can your team provide an instructional video on installation and deployment?

Thank You and Best Regard.

**Comment by RadhakrishnaJ** [comment]
Hello, 

We don't have videos yet.
We feel our documentation of Setup and download is sufficient. Along with troubleshoot section our document should cover all the required steps in detail. 

Please start with [Getting started](https://github.com/HewlettPackard/swarm-learning#getting-started).
