### ISSUE TITLE
Can not use GPU

### ISSUE THREAD

**Issue by smduan** [HewlettPackard/swarm-learning#67]
Dear RadhakrishnaJ,

We have deployed the SL environment and successfully run the provided [mnist-pytorch](https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-pytorch) project.  

However, we failed to use the GPU by specifying the parameter _--gpu 0_ in the _run-sl_ command follow the documentation [mnist-pytorch](https://github.com/HewlettPackard/swarm-learning/tree/master/examples/mnist-pytorch). The SL still uses the CPU for training. We use the following command:
```
bash ./swarm-learning/bin/run-sl         \     
    --name=sl-1                         \
    --sl-platform=pyt                   \
    --host-ip=192.168.236.38            \     
    --sn-ip=192.168.236.38                  \
    --sn-api-port=11000                 \
    --sl-fs-port=16000                  \
    --data-dir=./examples/mnist-pytorch/app-data  \
    --model-dir=./examples/mnist-pytorch/model    \
    --model-program=mnist_pyt.py        \
    --apls-ip 192.168.236.38              \
    -serverAddress 192.168.236.38           \
    -genJoinToken   \
    --gpu  0
```

We use the following docker images:

```
REPOSITORY                                                             TAG       IMAGE ID       CREATED        SIZE
hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls           0.3.0     8a382f3a48be   6 months ago   870MB
hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sn             0.3.0     3587a7c0e083   6 months ago   872MB
hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/sl-pyt         0.3.0     a55b0e33f352   6 months ago   4.45GB
hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/spire-server   0.3.0     0860ccc9e996   6 months ago   144MB
```
Is this configuration correct? 

Can you help me configure SL correctly to use GPU?

Thank You and Best Regard.

**Comment by RadhakrishnaJ** [comment]
Hello,

Current Eval version does not support GPU usage with pyTorch models. 
When using pyTorch model don't specify gpu option.

**Comment by RadhakrishnaJ** [comment]
Closing this as there no update from user. Requesting user to raise new issue for any further support.
