### ISSUE TITLE
Cannot inspect or pull docker images after login successfully.

### ISSUE THREAD

**Issue by semi-hollow** [HewlettPackard/swarm-learning#70]
I met the set-up problem again in another ubuntu system. (Sorry to bother you with this simple question again.

I use the available account to login the docker repository.
And I run the same commandline in both my own ubnutu and another ubuntu.
In my ubuntu, it works well:
![image](https://user-images.githubusercontent.com/64388497/143824683-d08ca81e-e101-43f4-a1da-973d25940c43.png)

but in another ubnutu, some error happens, after login succeeded & export docker_content_trust=1.
![image](https://user-images.githubusercontent.com/64388497/143824952-b2af7442-786f-4b50-adff-3eb68fa4804d.png)

to check if the docker works well, i give a test on inspect another docker repository, both ubuntu give the right feedback:
![image](https://user-images.githubusercontent.com/64388497/143825133-c7d25f4e-eb7a-48c2-9105-b153226136d4.png)

(p.s. the only difference between these two ubuntu system is i have changed the default docker image and container location in lab ubuntu.

**Comment by RadhakrishnaJ** [comment]
Hello,

can you revert back lab ubuntu system default docker image and container location and confirm whether it is working or not?

**Comment by semi-hollow** [comment]
> Hello,
> 
> can you revert back lab ubuntu system default docker image and container location and confirm whether it is working or not?

OK，I‘ll try that tomorrow. Thank you for this suggestion .

**Comment by semi-hollow** [comment]
problem solved. Thank you!
