### ISSUE TITLE
Can Swarm learning node change parameters of SwarmCallback dynamically?

### ISSUE THREAD

**Issue by zl8255** [HewlettPackard/swarm-learning#71]
Hello,
Can I change parameters of SwarmCallback dynamically?
I'm considering some scenarios that the weights of some nodes may change due to some reasons in the swarm training process, so I want to change the node dynamically.
I have seen in SwarmCallback ,there are two parameters can satisify my needs. One is "checkin_model_on_train_end" which specifies the merge behaviour of a SL node after it has achieved stopping criterion and it is waiting for all other peers to complete their training. The other is "node_weightage" which specifies a number between 0-100 to indicate the relative importance of this node compared to other nodes.
So what I want to do is change these two parameters dynamically so that can simulated real environment training. But I do not know how can I change these.  Can you give me some suggestions or can I instantiate an swarm_callback object in each epoch?

Thank You and Best Regard.

**Comment by daishu-li** [comment]
@zl8255 hello, have you install swarm-learning successfully? I have some questions, can I ask you for advice?

**Comment by zl8255** [comment]
> @zl8255 hello, have you install swarm-learning successfully? I have some questions, can I ask you for advice?

Yes, what's the problem？

**Comment by daishu-li** [comment]
@zl8255  Can you share a video explaining how to install the entire platform

**Comment by RadhakrishnaJ** [comment]
Hello, 

Currently Swarm expects same ML model and parameters across all nodes. 
[FAQ](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#can-each-swarm-learning-node-run-a-different-ml-program-and-parameters)

Currently we don't video which can shared across, will add once it is available.

**Comment by zl8255** [comment]
@RadhakrishnaJ
Thanks for your reply. And I also want to know the effect of parameter “node_weightage". Its range is0-100. How the number indicate the relative importance of this node compared to other nodes? In my opinion, the merge algorithms is averaging, so the importance of this node compared to other nodes will affect the merge process?

**Comment by zl8255** [comment]
@daishu-li   I install the entire platform just according to the guidance.  What is the specific problem？

**Comment by daishu-li** [comment]
@zl8255 Hi! I have installed the swarm learning successfully. But I can't run the quick start example 'mnist-keras' . Moreover, the  host ip is 127.0.01. So, the APLS_IP is 127.0.0.1. However, the guidance notices that "Do NOT use localhost/127.0.0.1". How can I deal with this situation? 
![image](https://user-images.githubusercontent.com/74223978/144804355-6ad48c0b-9f6b-415f-a89f-32b5a2aef872.png)
![image](https://user-images.githubusercontent.com/74223978/144805110-e57dbbcf-9031-4a40-8cdf-a268a29e0518.png)


I notice the error "run-sl: cannot contact SPIRE Server"
How can I solve it?

**Comment by zl8255** [comment]
@daishu-li Do you run APLS service? Start the APLS container using "swarm-learning-install-dir/swarm-learning/bin/run-apls --apls-port=5814"

**Comment by daishu-li** [comment]
@zl8255 I have run the APLS service.
![image](https://user-images.githubusercontent.com/74223978/144808727-94511393-5f63-4021-8501-f00922824d66.png)

**Comment by zl8255** [comment]
@daishu-li  The guidance notices that "Do NOT use localhost/127.0.0.1". So you can try the host IP in  the LAN

**Comment by daishu-li** [comment]
@zl8255 sorry, I don't know much about the it. How to perform this operation?

**Comment by zl8255** [comment]
@daishu-li  use the command "ifconfig" and have a try

**Comment by RadhakrishnaJ** [comment]
> @RadhakrishnaJ Thanks for your reply. And I also want to know the effect of parameter “node_weightage". Its range is0-100. How the number indicate the relative importance of this node compared to other nodes? In my opinion, the merge algorithms is averaging, so the importance of this node compared to other nodes will affect the merge process?

YES, node_weightage parameters can be set differently for each node. Merge process uses it accordingly. The Final model will be realtively biased towards higher node_weightage node than lower node_weightage node.

**Comment by zl8255** [comment]
The problem has been solved

**Comment by RadhakrishnaJ** [comment]
@zl8255, could you please confirm have you got answer for your queries here? Please let me know if you are looking for any support.

**Comment by zl8255** [comment]
@RadhakrishnaJ   
Yes, I have got answer for my question. Thank you very much for your reply.
Best Regard.

**Comment by zl8255** [comment]
@RadhakrishnaJ   
Yes, I have got answer for my question. Thank you very much for your reply.
Best Regard.

**Comment by RadhakrishnaJ** [comment]
@zl8255, Thanks for the confirmation. Closing this issue.
