### ISSUE TITLE
Is it possible to have multiple (more than 3) SL-nodes at only one SN, Spire and License-Node?

### ISSUE THREAD

**Issue by WerOle** [HewlettPackard/swarm-learning#73]
#  Issue description
- issue description: I try to setup my own Swarm-network, in the given examples 2 SL-Nodes are connected to only one License Server, Spire Server and SN-Node. When starting/connecting my 3rd or 4th SL-Node an error occurs (something like could not start new thread).
- occurrence - consistent or rare: consistent
- error messages: see image
- commands used for starting containers: run-sl script with parameters (see image)
- docker logs [APLS, SPIRE, SN, SL, SWCI]: SL-Node see image, SN-Node:

```
[363.968s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:798)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:937)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:129)
	at com.hp.autopassj.net.HeartBeatManager$HeartBeatTask.run(HeartBeatManager.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[484.001s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.
```

# OS and ML Platform
- details of host OS: Ubuntu 20.04
- details of ML platform used: PyTorch
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 1 machine, 4 SL, 1 SN

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses? Yes
- If Multiple systems are used, can each system access every other system? Not used
- Is Password-less SSH configuration setup for all the systems? Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? Yes
- Is the user id a member of the docker group? Yes

# Additional notes
- Are you running documented example without any modification? Example did run. It is also working with only 2 SL nodes.
- Add any additional information about use case or any notes which supports for issue investigation: 

## NOTE: Create an archive with supporting artifacts and attach to issue, whenever applicable.
![Bildschirmfoto 2022-01-04 um 10 20 34](https://user-images.githubusercontent.com/20433037/148039149-f0a6e180-018b-4c38-a1b6-1ca4254e4b59.png)

THANK YOU VERY MUCH!

**Comment by RadhakrishnaJ** [comment]
Hello, are you sure you have licenses available to start additional SL nodes? License management page will show you the limits. 

If license capacity available for SL resource, then please copy the commands you have used to start SN, SL nodes.

**Comment by WerOle** [comment]
Hi, thanks for the fast reply!

As you can see in the following image I'm using eval-license and have enough available (Should work for 2 SN nodes and 13 SL nodes, shouldn't it?)

![Bildschirmfoto 2022-01-05 um 11 30 48](https://user-images.githubusercontent.com/20433037/148202966-c741c2b5-cf41-4fb1-b5ff-47eb9a22a5ba.png)

I am using the following commands (replaced individual names by more common ones):

APLS:
```
swarm-learning/bin/run-apls --apls-port=5814
```
SPIRE:
```
sudo docker network create -d bridge covid-net
swarm-learning/bin/run-spire-server -d --name node-spire --network covid-net
```

1x SN:
```
swarm-learning/bin/run-sn -d --name node-sn --network covid-net --apls-ip=<LOCAL-IP-APLS> --host-ip node-sn --sentinel-ip node-sn --serverAddress node-spire -genJoinToken
```

4x SL:
```
swarm-learning/bin/run-sl --name node-1-sl --network covid-net --apls-ip=<IP-APLS> --data-dir=decentral/node_1/data/ --model-dir=decentral/node_1/model/ --model-program=decentral_training.py --host-ip=node-1-sl --sn-ip node-sn --sl-platform PYT --serverAddress node-spire -genJoinToken

swarm-learning/bin/run-sl --name node-2-sl --network covid-net --apls-ip=<IP-APLS> --data-dir=decentral/node_2/data/ --model-dir=decentral/node_2/model/ --model-program=decentral_training.py --host-ip=node-2-sl --sn-ip node-sn --sl-platform PYT --serverAddress node-spire -genJoinToken

swarm-learning/bin/run-sl --name node-3-sl --network covid-net --apls-ip=<IP-APLS> --data-dir=decentral/node_3/data/ --model-dir=decentral/node_3/model/ --model-program=decentral_training.py --host-ip=node-3-sl --sn-ip node-sn --sl-platform PYT --serverAddress node-spire -genJoinToken

swarm-learning/bin/run-sl --name node-4-sl --network covid-net --apls-ip=<IP-APLS> --data-dir=decentral/node_4/data/ --model-dir=decentral/node_4/model/ --model-program=decentral_training.py --host-ip=node-4-sl --sn-ip node-sn --sl-platform PYT --serverAddress node-spire -genJoinToken
```

Am I doing something wrong?
The only idea which came up to my mind is that some settings for the Java Environment of the machine are limiting the License Server to much. Could this be a reason?
Thanks again!

**Comment by RadhakrishnaJ** [comment]
Could you please copy docker logs of SL container which has this error?

**Comment by WerOle** [comment]
When starting 4 SL nodes I got following errors on 2 different nodes:

![Bildschirmfoto 2022-01-06 um 09 27 20](https://user-images.githubusercontent.com/20433037/148352884-99961caa-6b36-4f0a-a4bb-7e8fb0e650b7.png)

![Bildschirmfoto 2022-01-06 um 09 27 46](https://user-images.githubusercontent.com/20433037/148352904-c841d873-48b3-41bf-af74-39cafc882c96.png)

**Comment by RadhakrishnaJ** [comment]
Is your model code same when running with 2 nodes and 4 nodes? 
When using 2 nodes you could able to successfully complete swarm training?
Not able to get full sequence with screenshots attached, please provide log (txt) file obtained using docker logs command.

**Comment by WerOle** [comment]
Hi, yes of course it's working with only two nodes ;) You can see it in the following logs (1x SN, 2x SL):

[node-sn_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828150/node-sn_log.txt)
[node-1-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828152/node-1-sl_log.txt)
[node-2-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828178/node-2-sl_log.txt)

The only change I made from 2 to 4 SL-Nodes is to set minimum-peers to 4. I could skip that but than the nodes would start training even if one node is crashing...

In the following files I provide the logs for 1xSN and 4xSL ... as you can see the error-message (at node 4) is slightly different than above, which means to me that there is no error in code but maybe in setup. Am I wrong?
[4_node-sn_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828155/4_node-sn_log.txt)
[4_node-1-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828156/4_node-1-sl_log.txt)
[4_node-2-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828157/4_node-2-sl_log.txt)
[4_node-3-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828159/4_node-3-sl_log.txt)
[4_node-4-sl_log.txt](https://github.com/HewlettPackard/swarm-learning/files/7828171/4_node-4-sl_log.txt)

Thanks for your help!

**Comment by WerOle** [comment]
so finally I got this issue somehow solved. The problem was the limited server resources due to other running threads. It was not related to CPU usage or less RAM but to maximum of running threads parallel. I managed to run 5 SL nodes so this will be enough for my purpose. Thank you again for your time, maybe this can help someone else also testing multiple SL nodes at one machine.
Cheers!
