### ISSUE TITLE
Encounter ssh error "ssh: Could not resolve hostname..." or need input password when building sn or sl.

### ISSUE THREAD

**Issue by Typepluto** [HewlettPackard/swarm-learning#75]
#  Issue description
- issue description: Encounter ssh error "ssh: Could not resolve hostname..." or need input password when building sn or sl.
- occurrence - consistent or rare:  consistent
- error messages: 
![issue_4](https://user-images.githubusercontent.com/67870603/148731812-78b84bb7-d5d2-4467-a9ea-7a12a7462fe2.JPG)
![issue_1](https://user-images.githubusercontent.com/67870603/148731727-5a27a2cd-3ef8-4d50-a619-be414a3f7856.JPG)

- commands used for starting containers: 
- docker logs [APLS, SPIRE, SN, SL, SWCI]: none

# OS and ML Platform
- details of host OS: Ubuntu
- details of ML platform used: Ubuntu
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses? Yes
- If Multiple systems are used, can each system access every other system? Yes
- Is Password-less SSH configuration setup for all the systems? Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them? Yes
- Is the user id a member of the docker group? Yes

# Additional notes
- Are you running documented example without any modification? No
- Add any additional information about use case or any notes which supports for issue investigation: 
a.This machine can successfully ssh SPIRE Server by the below command.
![issue_2](https://user-images.githubusercontent.com/67870603/148732194-8a89a7f4-34b5-45dc-8b94-ca855cdf6509.JPG)
b.But if using the below command will ask to input the password. And even inputting the correct password still asks to input the password.
![issue_3](https://user-images.githubusercontent.com/67870603/148732299-889f5bd4-66c3-4a5e-ac3e-e1a10d2bf824.JPG)
c.
![issue_5](https://user-images.githubusercontent.com/67870603/148732929-95d71948-207a-4c04-b7c7-a1093c6cd396.JPG)

**Comment by girisairam450** [comment]
Hi @Typepluto 

Thanks for taking your time and testing the scenarios mentioned in the pull request (https://github.com/HewlettPackard/swarm-learning/pull/74) Usually the behavior of using **ssh ssh://${user}${3}${port}** and **ssh ${user}${3} -p ${port}** should be same. We have tried out both the ways and both work the same. we are NOT seeing the issue here and it works fine. However, changing back to common usage might impact other users. Since the issue seems specific to your machine, We recommend you to have this proposed change locally.

Regards
Giri

**Comment by Typepluto** [comment]
Hi @girisairam450 

Could you share your ssh version? Maybe it's a version issue.
Here is my ssh version:
`OpenSSH_7.6p1 Ubuntu-4ubuntu0.3, OpenSSL 1.0.2n  7 Dec 2017`

Regards
Po-Yi

**Comment by girisairam450** [comment]
Hi @Typepluto 

Sure, I have checked on our systems with `ssh -v localhost` and most of them are using ssh version `OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f 31 Mar 2020` and above. Please try to upgrade your ssh and see if the issue still persists.

Thanks and Regards
Giri

**Comment by Typepluto** [comment]
Hi @girisairam450 

This issue can't duplicate after I update my ssh version to `OpenSSH_8.4p1, OpenSSL 1.1.1  11 Sep 2018`.
Thank you for your time.

Regards
Po-Yi
