### ISSUE TITLE
MNIST-Keras issue

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#8]
Hi,

I run this command for MNIST-keras for the node 1 and it occurs this issue, what should I do to solve this?

![image](https://user-images.githubusercontent.com/38574065/123534596-201ac180-d6d3-11eb-919e-34734d18da54.png)

**Comment by suresh-ls** [comment]
From the error, it looks like the SL container is not able to reach the License Sever...

1) Hope you are running this on the same node where you have started the License Server ?

Try running a 'docker ps | grep swarm' and ensure all the swarm learning containers are running.  We should see 2 of these containers:

$ docker ps | grep swarm
27d3d2c4b93c   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/spire-server:0.3.0   "/spire/bin/launcher"    4 minutes ago   Up 4 minutes                            node-spire

2c7666156e08   hub.myenterpriselicense.hpe.com/hpe_eval/swarm-learning/apls:0.3.0           "/opt/autopass/Autop…"   2 weeks ago     Up 2 weeks     0.0.0.0:5814->5814/tcp   optimistic_booth

2) If above is fine, then check if you have set all 4 environment variables (including  the APLS_IP is set correctly to the IP address of the machine running the License Server) in the terminal were you are running ?

and then run the 'run-sl' script again.

**Comment by difan0224** [comment]
![image](https://user-images.githubusercontent.com/38574065/123535737-953dc500-d6da-11eb-94db-45fa4138fc6f.png)
This is what I got. Is this correct?

I would like to ask do i need to set up HPE AutoPass License Server Client Users? Like in Pool Management?

Thanks.

**Comment by suresh-ls** [comment]
Yes, that's sounds fine and all the required containers are running.   Nothing needs to be done manually for license server clients (like SN, SL).

Can you confirm on point 1 & 2 from my prev. response ? 
1. Hope you are running run-sl script on the same node where you have started the License Server ?
2. Is all the 4 env variables are set ?  If yes, give the o/p of the "echo" of the 4 variables ?

3) Also, what system are you running this ?  OS version ?

**Comment by difan0224** [comment]
Hello, I have fixed the problem and I close it.
