### ISSUE TITLE
Encounter "ModuleNotFoundError: No module named 'cv2'" fail while import cv2 in sl-pyt:0.3.0 image.

### ISSUE THREAD

**Issue by Typepluto** [HewlettPackard/swarm-learning#81]
#  Issue description
- issue description: Encounter "ModuleNotFoundError: No module named 'cv2'" fail while import cv2 in sl-pyt:0.3.0 image.
- occurrence - consistent or rare: consistent 
- error messages: ModuleNotFoundError: No module named 'cv2
- commands used for starting containers: 
- docker logs [APLS, SPIRE, SN, SL, SWCI]: 

# OS and ML Platform
- details of host OS: ubuntu
- details of ML platform used: PyTorch
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses?  Yes
- If Multiple systems are used, can each system access every other system? 
- Is Password-less SSH configuration setup for all the systems? 
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them?
- Is the user id a member of the docker group? Yes

# Additional notes
- Are you running documented example without any modification? No
- Add any additional information about use case or any notes which supports for issue investigation:

**Comment by oliversaldanha25** [comment]
You need to create a docker image. which will import the cv2 module.

**Comment by RadhakrishnaJ** [comment]
Please follow [Additional packages installation ](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#can-one-add-new-python-packages-in-swarm-learning)

**Comment by Typepluto** [comment]
Sorry for replying late.

But as you mention at [supported Python packages](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/FAQ.md#what-are-the-supported-python-packages-in-swarm-learning). opencv-python package should be supported.
