### ISSUE TITLE
Encounter "TypeError: new(): data must be a sequence (got numpy.float64)" while Merging ... in sl node.

### ISSUE THREAD

**Issue by Typepluto** [HewlettPackard/swarm-learning#82]
#  Issue description
- issue description: 
Encounter "TypeError: new(): data must be a sequence (got numpy.float64)" while Merging ... in sl node.

  SwarmCallback object:

  ` swarmCallback = SwarmCallback(sync_interval=128, min_peers=2, val_batch_size=128, model_name='ich_test', model=model, use_adaptive_sync=False)`
  
  Model object:
  ```
    model_func = pretrainedmodels.__dict__['se_resnext101_32x4d']
    model = model_func(num_classes=1000, pretrained=None)
    model.load_state_dict(torch.load('./se_resnext101_32x4d-3b2fe3d8.pth'))
    model.avg_pool = nn.AdaptiveAvgPool2d(1)
    model.last_linear = nn.Linear(
        model.last_linear.in_features,
        6,
    )
  ```
- occurrence - consistent or rare: consistent 
- error messages: 
```
Traceback (most recent call last):
  File "ich.py", line 13, in <module>
    train('/platform/swarmml/model', 1)
  File "ich.py", line 8, in train
    workdir=base, config='./config_11.py', epochs=epochs)
  File "/platform/swarmml/model/src/cnn/main.py", line 84, in main
    metrics, datasetSize = train(cfg, model, device)
  File "/platform/swarmml/model/src/cnn/main.py", line 154, in train
    swarmCallback.on_train_begin()
  File "swarm.py", line 266, in swarm.SwarmCallback.on_train_begin
  File "swarm.py", line 279, in swarm.SwarmCallback.do_sync
  File "swarmblackboard.py", line 1297, in swarmblackboard.swarmblackboard.rendezvous
  File "swarmblackboard.py", line 1082, in swarmblackboard.swarmblackboard.checkout
  File "swarm.py", line 403, in swarm.SwarmCallback.update_model_and_calculate_local_loss
  File "swarm.py", line 393, in swarm.SwarmCallback.loadModelWeightsFromDict
TypeError: new(): data must be a sequence (got numpy.float64)
```
- commands used for starting containers: 
- docker logs [APLS, SPIRE, SN, SL, SWCI]: 
[ich_sw.log](https://github.com/HewlettPackard/swarm-learning/files/7901588/ich_sw.log)

# OS and ML Platform
- details of host OS: 
- details of ML platform used: 
- details of Swarm learning Cluster (Number of machines, SL nodes, SN nodes): 

# Quick Checklist: Respond [Yes/No]
- APLS server web GUI shows available Licenses?Yes
- If Multiple systems are used, can each system access every other system?Yes
- Is Password-less SSH configuration setup for all the systems?Yes
- If GPU or other protected resources are used, does the account have sufficient privileges to access and use them?
- Is the user id a member of the docker group?

# Additional notes
- Are you running documented example without any modification?No
- Add any additional information about use case or any notes which supports for issue investigation:

**Comment by RadhakrishnaJ** [comment]
Could you please confirm your model is training when swarm callback is disabled?

**Comment by RadhakrishnaJ** [comment]
Closing this as it seems to be dataset creation issue.
