### ISSUE TITLE
How to contact the developer to join in the communication channel?

### ISSUE THREAD

**Issue by crownk1997** [HewlettPackard/swarm-learning#83]
Dear developer, I am a PhD student from The Hong Kong University of Science and Technology and my research topic is distributed machine learning. I am quite interested in this software. However, I found that the communication channel link does not work well. It seems that the source code of Swarm Node is not published. I really want to join in you and do this project. My mentor also agree with that. Could you please tell me how to contribute this software especially on the application of blockchain and merging algorithms? Thank you so much!

**Comment by RadhakrishnaJ** [comment]
Good to know you are interest on using Swarm learning for your research. 
Could you please explain which communication channel link didn't work for you?

**Comment by crownk1997** [comment]
> Good to know you are interest on using Swarm learning for your research. Could you please explain which communication channel link didn't work for you?

Thank you for your reply. I tried to join in the channel by using your provided link before and I used my HEP account email to sign in. However, it always told me the incorrect email address and there was no account on HPE tied to my email address. I am very sure that I can use it sign in through this https://www.hpe.com/us/en/home.html. Thank you in advance for your support and I am eager to start my research on this topic as soon as possible.

**Comment by crownk1997** [comment]
> Good to know you are interest on using Swarm learning for your research. Could you please explain which communication channel link didn't work for you?

The following link provided in the section of getting in touch.
https://hpe.enterprise.slack.com/?redir=%2Fr-t1723025465828%3Fredir%3D%252Farchives%252FC02PWRJPWVD

**Comment by crownk1997** [comment]
> Sorry for the delayed response. We will look at slack channel issue first. Please give us sometime to contact you.

I am looking forward to your further reply. We would like to start our research at this topic as soon as possible. Thanks.

**Comment by crownk1997** [comment]
> Sorry for the delayed response. We will look at slack channel issue first. Please give us sometime to contact you.

Hi, I have already accepted your invitation. However, it seems that the invitation is canceled by Hewlett Packard Enterprise. I am not sure what the problem is. Could you please give me some suggestion? Thanks.

**Comment by crownk1997** [comment]
Hello?

**Comment by MZW99** [comment]
I have the same problem. I can't join the slack channel with my email address. Have you solved this problem?

**Comment by crownk1997** [comment]
> I have the same problem. I can't join the slack channel with my email address. Have you solved this problem?

Not yet. The invitation was canceled for twice.

**Comment by iArpanPatel** [comment]
Please note we have new Slack channel.
Join the [HPE Developer Slack Workspace](https://slack.hpedev.io/) and start a discussion in our [#hpe-swarm-learning](https://hpedev.slack.com/archives/C04A5DK9TUK) channel.
