### ISSUE TITLE
question on using gpu with tensorflow

### ISSUE THREAD

**Issue by semi-hollow** [HewlettPackard/swarm-learning#84]
I'm using tensorflow-gpu 2.x with cuda 11.2. 
The doc instruct that specify the --gpu parameter with 0 or all to run the code with gpu instead of cpu.
Do i need to specify the gpu in python code itself as normal or this is no more necessary only if i have set the gpu parameter while running run-sl ?
Thank you.

**Comment by RadhakrishnaJ** [comment]
run-sl should specify gpus as mentioned our documentation.
