### ISSUE TITLE
mnist example cannot running properly

### ISSUE THREAD

**Issue by L1n111ya** [HewlettPackard/swarm-learning#85]
when I run two SL nodes at the same time, there are some problems. the terminals running these two SL nodes are shown as follows：
![屏幕截图 2022-02-10 011535](https://user-images.githubusercontent.com/73583645/153255586-3f07dff1-1f84-4c12-b853-a42996aca694.jpg)
![屏幕截图 2022-02-10 011554](https://user-images.githubusercontent.com/73583645/153255601-cdedcc44-8dfe-498f-a550-cddbace8a49a.jpg)
and the web shown as follows:
![屏幕截图 2022-02-10 011610](https://user-images.githubusercontent.com/73583645/153255701-9751b7a7-0539-4026-bd59-2545be907360.jpg)
details of host os:ubuntu 20.10(not macOS)
Could you please help me？I'll be much appreciated.
Best regrads.

**Comment by yzzer123** [comment]
I also have problems about the licenses install

**Comment by L1n111ya** [comment]
> do you have wechat account ? we can contact further

Sure. Could you please send your wechat account to my email`L1n111ya@163.com`? Looking forward to your email.

**Comment by L1n111ya** [comment]
> Sure. Could you please send your wechat account to my email`L1n111ya@163.com`? Looking forward to your email.

**Comment by RadhakrishnaJ** [comment]
Hello, 
Our team doesn't use wechat. 
Please use official slack channel mentioned in readme documentation.

Please go through "Getting Started" section once again. Our documentation should help you get through the errors you had faced.
If you still have same error, then please send docker logs of containers along with run commands used.

**Comment by L1n111ya** [comment]
> Hello, Our team doesn't use wechat. Please use official slack channel mentioned in readme documentation.
> 
> Please go through "Getting Started" section once again. Our documentation should help you get through the errors you had faced. If you still have same error, then please send docker logs of containers along with run commands used.
Thank you for your reply. I have gone through "Gettng Started" sention once again, but i also got the same errors. The docker logs of containers are as follows:
![屏幕截图 2022-02-17 014436](https://user-images.githubusercontent.com/73583645/154325201-64b3c207-bdd2-4ac1-b957-f17e350b4a69.png)
![屏幕截图 2022-02-17 014457](https://user-imag
![屏幕截图 2022-02-17 014515](https://user-images.githubusercontent.com/73583645/154325297-4a1fcd34-2f9f-42e4-a3e2-3e0f39f0e681.png)
es.githubusercontent.com/73583645/154325274-c2df7124-3a07-4bb1-9e79-e8893f3d4bf1.png)
I still didn't find the solutions, can anyone give me some advice?

**Comment by RadhakrishnaJ** [comment]
It seems SL count able to reach SN API port. Are you running documented example as is or modified? 
Please send us the commands you have used for running SN and SL. 
Use our  [Issue template doc](https://github.com/HewlettPackard/swarm-learning/blob/master/.github/ISSUE_TEMPLATE/swam-learning-issue-reporting-template.md) avoid multiple rounds discussions.
