### ISSUE TITLE
16 sl nodes

### ISSUE THREAD

**Issue by difan0224** [HewlettPackard/swarm-learning#90]
I notice in the license, the capacity for sl is 16 and sn is 4. Any recommendation set up to fully use these 16 sl nodes? Thanks.

**Comment by IMOKURI** [comment]
I believe one SN can use multiple SLs.

According to the documentation, up to 4 SLs in one SN is recommended.

https://github.com/HewlettPackard/swarm-learning/blob/17994e0e9bd822995707c852b9ea40a052af706d/docs/User/Frequently_asked_questions.md#-how-many-sls-can-connect-with-a-sn

However, I believe the current license for the community version is up to 5 nodes for both.

 https://github.com/HewlettPackard/swarm-learning/blob/17994e0e9bd822995707c852b9ea40a052af706d/docs/Install/Install_the_License_Server.md

**Comment by RadhakrishnaJ** [comment]
@IMOKURI - Agree with your response. Thanks for your response. 

As there is no issue to be discussed here. Closing this ticket.
