### ISSUE TITLE
Unable to get trial license, invalid URL in setup.md

### ISSUE THREAD

**Issue by htjain** [HewlettPackard/swarm-learning#93]
https://myenterpriselicense.hpe.com/cwp-ui/evaluation/HPE-SWARM/0.3.0/null link in [setup.md](https://github.com/HewlettPackard/swarm-learning/blob/master/docs/setup.md) is invalid. 

![image](https://user-images.githubusercontent.com/46592577/162819460-0e0a586f-2269-43cf-812b-58fd4a3ca9fc.png)

Can someone please fix it and point me to correct URL?

**Comment by suresh-ls** [comment]
The URL is fixed.   Could you please try now..

![image](https://user-images.githubusercontent.com/63008946/170470185-c055e6c8-0dc4-412f-aded-006e2c3f7793.png)
