### ISSUE TITLE
How the swarm learning works

### ISSUE THREAD

**Issue by L1n111ya** [HewlettPackard/swarm-learning#94]
I'm so sorry to bother you. Could you please tell me how the swarm learning works? Is all the swarm nodes network aggregate the model parameter as a ring? Just like the node A gives its parameter to the node B, then B gives the aggregated-parameter to the C, and C gives the final-aggregated-parameter to A. Or it worked by some other way? I would appreciate it if you could reply.

**Comment by StefDS** [comment]
Additional info is also available on [HPE's Swarm Learning website](https://www.hpe.com/us/en/solutions/artificial-intelligence/swarm-learning.html).

**Comment by L1n111ya** [comment]
> 

Thank you for your reply.
