### ISSUE TITLE
ZIP files cannot be opened

### ISSUE THREAD

**Issue by misterletter** [HewlettPackard/swarm-learning#96]
I have downloaded two files from the HPE Software Center: HPE_Swarm_Learning_1.0.0_Opensource_SN_and_SWCI_Components.zip
HPE_Swarm_Learning_1.0.0_Opensource_SL_and_SWOP_Components.zip

Unfortunately, I am not able to unzip these files. It throws the following error:
Archive:  HPE_Swarm_Learning_1.0.0_Opensource_SN_and_SWCI_Components.zip
warning [HPE_Swarm_Learning_1.0.0_Opensource_SN_and_SWCI_Components.zip]:  1692918522 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [HPE_Swarm_Learning_1.0.0_Opensource_SN_and_SWCI_Components.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

Could you please recheck them? Thanks in advance!

**Comment by RadhakrishnaJ** [comment]
These are not Swarm Learning product images, these are open components used in Swarm Learning product development. There won't be any need to download these for swarm product usage. 

Please refer Getting started section, it has been now updated with 1.0.0 version.
